"""Subclass of ChooseTreasure_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChooseTreasure_Dialog
class ARCedChooseTreasure_Dialog( ARCed_Templates.ChooseTreasure_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChooseTreasure_Dialog.__init__( self, parent )
	
	# Handlers for ChooseTreasure_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
