"""Subclass of EventPage_Panel, which  generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing EventPage_Panel
class ARCedEventPage_Panel( ARCed_Templates.EventPage_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.EventPage_Panel.__init__( self, parent )
	
