"""Subclass of ConditionalBranch_Dialog, which is generated by wxFormBuilder."""

import wx
from Core.Database import ARCed_Templates as Templates

# Implementing ConditionalBranch_Dialog
class ConditionalBranch_Dialog( Templates.ConditionalBranch_Dialog ):
	def __init__( self, parent ):
		Templates.ConditionalBranch_Dialog.__init__( self, parent )
	
	# Handlers for ConditionalBranch_Dialog events.
	def radioButtonSwitch_CheckedChanged( self, event ):
		# TODO: Implement radioButtonSwitch_CheckedChanged
		pass
	
	def radioButtonVariable_CheckChanged( self, event ):
		# TODO: Implement radioButtonVariable_CheckChanged
		pass
	
	def radioButtonConstant_CheckChanged( self, event ):
		# TODO: Implement radioButtonConstant_CheckChanged
		pass
	
	def radioButtonSelfSwitch_CheckChanged( self, event ):
		# TODO: Implement radioButtonSelfSwitch_CheckChanged
		pass
	
	def radioButtonTimer_CheckChanged( self, event ):
		# TODO: Implement radioButtonTimer_CheckChanged
		pass
	
	def radioButtonActor_CheckChanged( self, event ):
		# TODO: Implement radioButtonActor_CheckChanged
		pass
	
	def radioButtonInParty_CheckChanged( self, event ):
		# TODO: Implement radioButtonInParty_CheckChanged
		pass
	
	def radioButtonName_CheckChanged( self, event ):
		# TODO: Implement radioButtonName_CheckChanged
		pass
	
	def radioButtonSkill_CheckChanged( self, event ):
		# TODO: Implement radioButtonSkill_CheckChanged
		pass
	
	def radioButtonWeapons_CheckChanged( self, event ):
		# TODO: Implement radioButtonWeapons_CheckChanged
		pass
	
	def radioButtonArmor_CheckChanged( self, event ):
		# TODO: Implement radioButtonArmor_CheckChanged
		pass
	
	def radioButtonState_CheckChanged( self, event ):
		# TODO: Implement radioButtonState_CheckChanged
		pass
	
	def radioButtonEnemy_CheckChanged( self, event ):
		# TODO: Implement radioButtonEnemy_CheckChanged
		pass
	
	def radioButtonAppeared_CheckChanged( self, event ):
		# TODO: Implement radioButtonAppeared_CheckChanged
		pass
	
	def radioButtonState_ValueChanged( self, event ):
		# TODO: Implement radioButtonState_ValueChanged
		pass
	
	def radioButtonCharacter_CheckChanged( self, event ):
		# TODO: Implement radioButtonCharacter_CheckChanged
		pass
	
	def radioButtonGold_CheckChanged( self, event ):
		# TODO: Implement radioButtonGold_CheckChanged
		pass
	
	def radioButtonItem_CheckChanged( self, event ):
		# TODO: Implement radioButtonItem_CheckChanged
		pass
	
	def radioButtonWeapon_CheckChanged( self, event ):
		# TODO: Implement radioButtonWeapon_CheckChanged
		pass
	
	def radioButtonButton_CheckChanged( self, event ):
		# TODO: Implement radioButtonButton_CheckChanged
		pass
	
	def radioButtonScript_CheckChanged( self, event ):
		# TODO: Implement radioButtonScript_CheckChanged
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
