"""Subclass of InputNumber_Dialog, which is generated by wxFormBuilder."""

import wx
from Core.Database import ARCed_Templates as Templates

# Implementing InputNumber_Dialog
class InputNumber_Dialog( Templates.InputNumber_Dialog ):
	def __init__( self, parent ):
		Templates.InputNumber_Dialog.__init__( self, parent )
	
	# Handlers for InputNumber_Dialog events.
	def comboBoxVariable_Clicked( self, event ):
		# TODO: Implement comboBoxVariable_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
