"""Subclass of Label_Dialog, which is generated by wxFormBuilder."""

import wx
from Core.Database import ARCed_Templates as Templates

# Implementing Label_Dialog
class Label_Dialog( Templates.Label_Dialog ):
	def __init__( self, parent ):
		Templates.Label_Dialog.__init__( self, parent )
	
	# Handlers for Label_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
