"""Subclass of ShowText_Dialog, which is generated by wxFormBuilder."""

import wx
from Core.Database import ARCed_Templates as Templates

# Implementing ShowText_Dialog
class ShowText_Dialog( Templates.ShowText_Dialog ):
	def __init__( self, parent ):
		Templates.ShowText_Dialog.__init__( self, parent )
	
	# Handlers for ShowText_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
