"""Subclass of ChangeMapSettings_Dialog, which is generated by wxFormBuilder."""

import wx
from Core.Database import ARCed_Templates as Templates

# Implementing ChangeMapSettings_Dialog
class ChangeMapSettings_Dialog( Templates.ChangeMapSettings_Dialog ):
	def __init__( self, parent ):
		Templates.ChangeMapSettings_Dialog.__init__( self, parent )
	
	# Handlers for ChangeMapSettings_Dialog events.
	def radioBoxPanorama_CheckChanged( self, event ):
		# TODO: Implement radioBoxPanorama_CheckChanged
		pass
	
	def comboBoxPanorama_Clicked( self, event ):
		# TODO: Implement comboBoxPanorama_Clicked
		pass
	
	def radioBoxFog_CheckChanged( self, event ):
		# TODO: Implement radioBoxFog_CheckChanged
		pass
	
	def comboBoxFog_Clicked( self, event ):
		# TODO: Implement comboBoxFog_Clicked
		pass
	
	def radioBoxBattleback_CheckChanged( self, event ):
		# TODO: Implement radioBoxBattleback_CheckChanged
		pass
	
	def comboBoxBattleback_Clicked( self, event ):
		# TODO: Implement comboBoxBattleback_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
