"""Subclass of TransferPlayer_Dialog, which is generated by wxFormBuilder."""

import wx
from Core.Database import ARCed_Templates as Templates

# Implementing TransferPlayer_Dialog
class TransferPlayer_Dialog( Templates.TransferPlayer_Dialog ):
	def __init__( self, parent ):
		Templates.TransferPlayer_Dialog.__init__( self, parent )
	
	# Handlers for TransferPlayer_Dialog events.
	def radioButtonDirect_CheckChanged( self, event ):
		# TODO: Implement radioButtonDirect_CheckChanged
		pass
	
	def comboBoxDirectAppointment_Clicked( self, event ):
		# TODO: Implement comboBoxDirectAppointment_Clicked
		pass
	
	def radioButtonVariables_CheckChanged( self, event ):
		# TODO: Implement radioButtonVariables_CheckChanged
		pass
	
	def comboBoxMapID_Clicked( self, event ):
		# TODO: Implement comboBoxMapID_Clicked
		pass
	
	def comboBoxMapX_Clicked( self, event ):
		# TODO: Implement comboBoxMapX_Clicked
		pass
	
	def comboBoxMapY_Clicked( self, event ):
		# TODO: Implement comboBoxMapY_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
