"""Subclass of AnimationCellProperties_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing AnimationCellProperties_Dialog
class AnimationCellProperties_Dialog(ARCed_Templates.AnimationCellProperties_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.AnimationCellProperties_Dialog.__init__( self, parent )
	
	# Handlers for AnimationCellProperties_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
