"""Subclass of BattleTest_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing BattleTest_Dialog
class ARCedBattleTest_Dialog( ARCed_Templates.BattleTest_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.BattleTest_Dialog.__init__( self, parent )
	
	# Handlers for BattleTest_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
