"""Subclass of ControlTimer_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ControlTimer_Dialog
class ARCedControlTimer_Dialog( ARCed_Templates.ControlTimer_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ControlTimer_Dialog.__init__( self, parent )
	
	# Handlers for ControlTimer_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
