"""Subclass of AddParameter_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing AddParameter_Dialog
class ARCedAddParameter_Dialog( ARCed_Templates.AddParameter_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.AddParameter_Dialog.__init__( self, parent )
	
	def buttonOK_Clicked( self, event ):
		""" End the dialog and return wx.ID_OK """
		self.EndModal(wx.ID_OK)
	
	def buttonCancel_Clicked( self, event ):
		""" End the dialog and return wx.ID_CANCEL """
		self.EndModal(wx.ID_CANCEL)
	
	
