"""Subclass of Skills_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates 
from ARCedChangeMaximum_Dialog import ARCedChangeMaximum_Dialog
from ARCedChooseGraphic_Dialog import ARCedChooseGraphic_Dialog
from ARCedChooseAudio_Dialog import ARCedChooseAudio_Dialog
from Core.RMXP import RGSS1_RPG as RPG
import Kernel
from Kernel import Manager as KM

# TEST
ARC_FORMAT = False

class ARCedSkills_Panel( ARCed_Templates.Skills_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.Skills_Panel.__init__( self, parent )
		global Config, DataSkills, DataAnimations, DataElements
		global DataStates, DataCommonEvents
		Config = Kernel.GlobalObjects.get_value('ARCed_config')
		try:
			proj = Kernel.GlobalObjects.get_value('PROJECT')
			DataSkills = proj.getData('Skills')
			DataAnimations = proj.getData('Animations')
			DataStates = proj.getData('States')
			DataElements = proj.getData('System').elements
			DataCommonEvents = proj.getData('Common Events')
		except NameError:
			Kernel.Log('Database opened before Project has been initialized', '[Database:SKILLS]', True)
			self.Destroy()
		icons = KM.get_component('IconManager').object
		imageList = wx.ImageList(14, 12)
		imageList.Add(icons.getBitmap('checkempty'))
		imageList.Add(icons.getBitmap('checkplus'))
		imageList.Add(icons.getBitmap('checkminus'))
		self.listCtrlStates.AssignImageList(imageList, wx.IMAGE_LIST_SMALL)
		font = wx.Font(8, wx.FONTFAMILY_TELETYPE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL)
		font.SetFaceName(Config.get('Misc', 'NoteFont')) 
		self.textCtrlNotes.SetFont(font)
		self.comboBoxIcon.SetCursor(wx.STANDARD_CURSOR)
		self.comboBoxMenuSE.SetCursor(wx.STANDARD_CURSOR)
		self.CreateControls()
		self.setRanges()
		self.SelectedSkill = DataSkills[self.FixedIndex(0)]
		self.refreshAll()
		self.listBoxSkills.SetSelection(0)

	def CreateControls( self ):
		self.ParameterControls = [
			self.spinCtrlAtkF, self.spinCtrlPdefF,
			self.spinCtrlMdefF, self.spinCtrlEvaF ]
		# Get main sizer to add to, and split parameters into rows of 4 each
		mainsizer = self.panelParameters.GetSizer()
		if ARC_FORMAT:
			params = Config.getlist('Misc', 'Parameters')
		else:
			params = ['STR', 'DEX', 'AGI', 'INT']
		rows = [params[i:i+4] for i in xrange(0, len(params), 4)]
		# Iterate through each of the rows and create the controls
		for row in rows:
			labelsizer = wx.BoxSizer(wx.HORIZONTAL)
			spinsizer = wx.BoxSizer(wx.HORIZONTAL)
			n = len(row)
			if n < 4:
				row.append(None)
				proportion = 25 * (4 - n)
			for param in row:
				if param != None:
					label = wx.StaticText( self.panelParameters, wx.ID_ANY, param + '-F:')
					label.Wrap( -1 )
					labelsizer.Add( label, 25, wx.ALL, 5 )
					spinctrl = wx.SpinCtrl( self.panelParameters, wx.ID_ANY, wx.EmptyString, style=wx.SP_ARROW_KEYS|wx.SP_WRAP)
					spinctrl.Bind(wx.EVT_SPINCTRL, Kernel.Protect(self.spinCtrlParameter_ValueChanged))
					self.ParameterControls.append(spinctrl)
					spinsizer.Add( spinctrl, 25, wx.BOTTOM|wx.RIGHT|wx.LEFT|wx.EXPAND, 5 )
				else:
					# Create a dummy filler
					dummy = wx.StaticText( self.panelParameters, wx.ID_ANY, '')
					dummy.Wrap(-1)
					labelsizer.Add(dummy, proportion, wx.ALL, 5)
					spinsizer.Add(dummy, proportion, wx.ALL, 5)
			mainsizer.Add( labelsizer, 0, wx.EXPAND, 5 )
			mainsizer.Add( spinsizer, 0, wx.EXPAND, 5 )



	def refreshSkillList( self ):
		''' Refreshes the values in the class wxListBox control '''
		self.listBoxSkills.Clear()
		for i, skill in enumerate(DataSkills):
			if not ARC_FORMAT and i == 0:
				continue
			digits = len(Config.get('GameObjects', 'Skills'))
			self.listBoxSkills.Append("".join([str(i).zfill(digits), ': ', skill.name]))
		self.listBoxSkills.SetSelection(0)

	def refreshAnimations( self ):
		self.comboBoxTargetAnimation.Clear()
		self.comboBoxUserAnimation.Clear()
		digits = len(Config.get('GameObjects', 'Animations'))
		start = self.FixedIndex(0)
		animations = [
			''.join([str(i).zfill(digits), ': ', DataAnimations[i].name]) for i in xrange(start, len(DataAnimations))]
		animations.insert(0, '(None)')
		self.comboBoxTargetAnimation.AppendItems(animations)
		self.comboBoxUserAnimation.AppendItems(animations)

	def refreshElements( self ):
		''' Clears and refreshes the list of elements in the checklist '''
		self.checkListElements.Clear()
		start = self.FixedIndex(0)
		names = DataElements[start:]
		self.checkListElements.InsertItems(names, 0)
		self.checkListElements.SetSelection(0)

	def refreshStates( self ):
		''' Clears and refreshes the list of states in the checklist '''
		self.listCtrlStates.DeleteAllItems()
		start = self.FixedIndex(0)
		names = [DataStates[i].name for i in xrange(start, len(DataStates))]
		self.listCtrlStates.InsertColumn(0, '')

		for i in xrange(len(names)):
			self.listCtrlStates.InsertStringItem(i, names[i], 0)

		#self.ColorizeStates()

	def refreshValues(self ):
		''' Resets the values of all the controls to reflect the selected skill '''
		skill = self.SelectedSkill
		self.textCtrlName.ChangeValue(skill.name)
		self.textCtrlDescription.ChangeValue(skill.description)
		self.comboBoxIcon.SetValue(skill.icon_name)
		self.comboBoxScope.SetSelection(skill.scope)
		self.comboBoxOccasion.SetSelection(skill.occasion)
		self.comboBoxUserAnimation.SetSelection(skill.animation1_id)
		self.comboBoxTargetAnimation.SetSelection(skill.animation2_id)
		self.comboBoxCommonEvent.SetSelection(skill.common_event_id)
		self.comboBoxMenuSE.SetValue(skill.menu_se.name)


		# TODO: Remove this. Something got screwed up converting
		if skill.power > 2147483647:
			skill.power = 0

		self.spinCtrlSPCost.SetValue(skill.sp_cost)
		self.spinCtrlPower.SetValue(skill.power) 
		self.spinCtrlHitRate.SetValue(skill.hit)
		self.spinCtrlVariance.SetValue(skill.variance)
		if ARC_FORMAT:
			# TODO: Implement
			pass
		else:
			# TEMP METHOD
			self.ParameterControls[0].SetValue(skill.atk_f)
			self.ParameterControls[1].SetValue(skill.pdef_f)
			self.ParameterControls[2].SetValue(skill.mdef_f)
			self.ParameterControls[3].SetValue(skill.eva_f)		
			self.ParameterControls[4].SetValue(skill.str_f)
			self.ParameterControls[5].SetValue(skill.dex_f)
			self.ParameterControls[6].SetValue(skill.agi_f)
			self.ParameterControls[7].SetValue(skill.int_f)
		for i in xrange(self.checkListElements.GetCount()):
			checked = skill.element_set
			if not ARC_FORMAT:
				checked = [i - 1 for i in checked]
			self.checkListElements.SetChecked(checked)

		if ARC_FORMAT:
			addstates = self.SelectedSkill.plus_state_set
			minusstates = self.SelectedSkill.minus_state_set
		else:
			addstates = [id - 1 for id in self.SelectedSkill.plus_state_set]
			minusstates = [id - 1 for id in self.SelectedSkill.minus_state_set]
		for i in xrange(self.listCtrlStates.GetItemCount()):
			if i in addstates:
				self.listCtrlStates.SetItemImage(i, 1)
			elif i in minusstates:
				self.listCtrlStates.SetItemImage(i, 2)
			else:
				self.listCtrlStates.SetItemImage(i, 0)

	def refreshAll( self ):
		self.refreshSkillList()
		self.refreshAnimations()
		self.refreshStates()
		self.refreshElements()
		self.refreshValues()

	def setRanges( self ):
		self.spinCtrlSPCost.SetRange(0, Config.getint('Actors', 'MaxSP'))
		max = Config.getint('Misc', 'MaxParamValue')
		self.spinCtrlPower.SetRange(-max, max)
		for spinctrl in self.ParameterControls:
			spinctrl.SetRange(0, max)

	def listBoxSkills_SelectionChanged( self, event ):
		index = self.FixedIndex(event.GetSelection())
		if DataSkills[index] == None:
			DataSkills[index] = RPG.Skill()
		self.SelectedSkill = DataSkills[index]
		self.refreshValues()

	def buttonMaximum_Clicked( self, event ):
		''' Shows dialog for changing the list capacity '''
		items = self.listBoxSkills.GetItems()
		currentMax = len(items)
		maxClasses = Config.getint('GameObjects', 'Skills')
		dlg = ARCedChangeMaximum_Dialog(self, currentMax, 1, maxClasses)
		if dlg.ShowModal() == wx.ID_OK:
			newMax = dlg.spinCtrlMaximum.GetValue()
			if newMax != currentMax: 
				if newMax > currentMax:
					newSkills = [None for i in xrange(newMax - currentMax)]
					digits = len(Config.get('GameObjects', 'Skills'))
					newLabels = [
						"".join([str(1 + currentMax + i).zfill(digits), 
						': ']) for i in xrange(newMax - currentMax)]
					DataSkills.extend(newSkills)
					self.listBoxSkills.InsertItems(newLabels, currentMax)
				else:
					if self.listBoxSkills.GetSelection() >= newMax:
						self.listBoxSkills.Select(newMax - 1)
					del DataSkills[newMax:currentMax]
					for i in reversed(range(currentMax)):
						if i >= newMax:
							self.listBoxSkills.Delete(i)
						else:
							break;
		dlg.Destroy()	

	def textCtrlName_TextChanged( self, event ):
		# TODO: Implement textCtrlName_TextChanged
		pass

	def comboBoxIcon_LeftClicked( self, event ):
		''' Opens dialog to select an icon for the selected skill '''
		self.listBoxSkills.SetFocus()
		icon = self.SelectedSkill.icon_name
		dlg = ARCedChooseGraphic_Dialog(self, 'Graphics/Icons', icon)
		if dlg.ShowModal() == wx.ID_OK:
			

			self.comboBoxIcon.SetValue(self.SelectedSkill.icon_name)
		dlg.Destroy()

	def textCtrlDescription_TextChange( self, event ):
		''' Set the selected skill's description '''
		self.SelectedSkill.description = event.GetString()

	def comboBoxScope_SelectionChanged( self, event ):
		''' Set the selected skill's scope '''
		self.SelectedSkill.scope = event.GetInt()

	def comboBoxUserAnimation_SelectionChanged( self, event ):
		''' Set the selected skill's user animation ID '''
		self.SelectedSkill.animation1_id = event.GetInt()

	def comboBoxMenuSE_Clicked( self, event ):
		''' Opens the dialog for selecting the audio file to use '''
		self.listBoxSkills.SetFocus()
		dlg = ARCedChooseAudio_Dialog(self, 'Audio/SE/', 0, self.SelectedSkill.menu_se)
		if dlg.ShowModal() == wx.ID_OK:
			self.SelectedSkill.menu_se = dlg.GetAudio()
			self.comboBoxMenuSE.SetValue(self.SelectedSkill.menu_se.name)
		dlg.Destroy()

	def comboBoxOccasion_SelectionChanged( self, event ):
		''' Set the selected skill's occasion '''
		self.SelectedSkill.occasion = event.GetInt()

	def comboBoxTargetAnimation_SelectionChanged( self, event ):
		''' Set the selected skill's target animation ID '''
		self.SelectedSkill.animation2_id = event.GetInt()

	def comboBoxCommonEvent_SelectionChanged( self, event ):
		''' Set the selected skill's SP cost '''
		self.SelectedSkill.common_event_id = event.GetInt()

	def spinCtrlSPCost_ValueChanged( self, event ):
		''' Set the selected skill's SP cost '''
		self.SelectedSkill.sp_cost = event.GetInt()

	def spinCtrlHitRate_ValueChanged( self, event ):
		''' Set the selected skill's hit rate '''
		self.SelectedSkill.hit = event.GetInt()

	def spinCtrlPower_ValueChanged( self, event ):
		''' Set the selected skill's power '''
		self.SelectedSkill.power = event.GetInt()

	def spinCtrlVariance_ValueChanged( self, event ):
		''' Set the selected skill's variance '''
		self.SelectedSkill.variance = event.GetInt()

	def spinCtrlParameter_ValueChanged( self, event ):
		index = self.ParameterControls.index(event.GetEventObject())
		if ARC_FORMAT:
			# TODO: Implement
			pass
		else:
			value = event.GetInt()
			if index == 0: self.SelectedSkill.atk_f = value
			elif index == 1: self.SelectedSkill.pdef_f = value
			elif index == 2: self.SelectedSkill.mdef_f = value
			elif index == 3: self.SelectedSkill.eva_f = value
			elif index == 4: self.SelectedSkill.str_f = value
			elif index == 5: self.SelectedSkill.dex_f = value
			elif index == 6: self.SelectedSkill.agi_f = value
			elif index == 7: self.SelectedSkill.int_f = value

	def checkListElements_CheckChanged( self, event ):
		''' Sets the IDs that are in the selected skills element set '''
		ids = [self.FixedIndex(id) for id in self.checkListElements.GetChecked()]
		self.SelectedSkill.element_set = ids

	def listCtrlStates_LeftClicked( self, event ):
		''' '''
		self.ChangeSkillStates(event, 1)

	def listCtrlStates_RightClicked( self, event ):
		''' '''
		self.ChangeSkillStates(event, -1)

	def ChangeSkillStates( self, event, increment ):
		''' '''
		id = self.listCtrlStates.HitTest(event.GetPosition())[0]
		if id >= 0:
			imgIndex = self.listCtrlStates.GetItem(id).GetImage()
			imgIndex = (imgIndex + increment) % 3
			self.listCtrlStates.SetItemImage(id, imgIndex)
			state_id = self.FixedIndex(id)
			if imgIndex == 0:
				if state_id in self.SelectedSkill.minus_state_set: 
					self.SelectedSkill.minus_state_set.remove(state_id)
				elif state_id in self.SelectedSkill.plus_state_set: 
					self.SelectedSkill.plus_state_set.remove(state_id)
			if imgIndex == 1:
				if state_id in self.SelectedSkill.minus_state_set: 
					self.SelectedSkill.minus_state_set.remove(state_id)
				self.SelectedSkill.plus_state_set.append(state_id)
			if imgIndex == 2:
				if state_id in self.SelectedSkill.plus_state_set: 
					self.SelectedSkill.plus_state_set.remove(state_id)
				self.SelectedSkill.minus_state_set.append(state_id)

	def textCtrlNotes_TextChanged( self, event ):
		# TODO: Implement textCtrlNotes_TextChanged
		pass


	@staticmethod
	def FixedIndex(index):
		''' Returns the correct starting index for game data structure depending on the current format '''
		if ARC_FORMAT:
			return index
		else:
			return index + 1