"""Subclass of ControlSelfSwitches_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ControlSelfSwitches_Dialog
class ARCedControlSelfSwitches_Dialog( ARCed_Templates.ControlSelfSwitches_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ControlSelfSwitches_Dialog.__init__( self, parent )
	
	# Handlers for ControlSelfSwitches_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
