"""Subclass of ShopProcessing_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ShopProcessing_Dialog
class ShopProcessing_Dialog(ARCed_Templates.ShopProcessing_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ShopProcessing_Dialog.__init__( self, parent )
	
	# Handlers for ShopProcessing_Dialog events.
	def listCtrlShopGoods_DoubleClick( self, event ):
		# TODO: Implement listCtrlShopGoods_DoubleClick
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
