"""Subclass of EventCommands1_Panel, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing EventCommands1_Panel
class EventCommands1_Panel( Templates.EventCommands1_Panel ):
	def __init__( self, parent ):
		Templates.EventCommands1_Panel.__init__( self, parent )
	
	# Handlers for EventCommands1_Panel events.
	def buttonShowText_Clicked( self, event ):
		# TODO: Implement buttonShowText_Clicked
		pass
	
	def buttonShowChoices_Clicked( self, event ):
		# TODO: Implement buttonShowChoices_Clicked
		pass
	
	def buttonInputNumber_Clicked( self, event ):
		# TODO: Implement buttonInputNumber_Clicked
		pass
	
	def buttonChangeTextOptions_Clicked( self, event ):
		# TODO: Implement buttonChangeTextOptions_Clicked
		pass
	
	def buttonChangeWindowskin_Clicked( self, event ):
		# TODO: Implement buttonChangeWindowskin_Clicked
		pass
	
	def buttonConditionalBranch_Clicked( self, event ):
		# TODO: Implement buttonConditionalBranch_Clicked
		pass
	
	def buttonWait_Clicked( self, event ):
		# TODO: Implement buttonWait_Clicked
		pass
	
	def buttonLoop_Clicked( self, event ):
		# TODO: Implement buttonLoop_Clicked
		pass
	
	def buttonBreakLoop_Clicked( self, event ):
		# TODO: Implement buttonBreakLoop_Clicked
		pass
	
	def buttonExitEventProcessing_Clicked( self, event ):
		# TODO: Implement buttonExitEventProcessing_Clicked
		pass
	
	def buttonCallCommonEvent_Clicked( self, event ):
		# TODO: Implement buttonCallCommonEvent_Clicked
		pass
	
	def buttonLabel_Clicked( self, event ):
		# TODO: Implement buttonLabel_Clicked
		pass
	
	def button_ClickedJumpToLabel( self, event ):
		# TODO: Implement button_ClickedJumpToLabel
		pass
	
	def buttonComment_Clicked( self, event ):
		# TODO: Implement buttonComment_Clicked
		pass
	
	def buttonScript_Clicked( self, event ):
		# TODO: Implement buttonScript_Clicked
		pass
	
	def buttonControlSwitches_Clicked( self, event ):
		# TODO: Implement buttonControlSwitches_Clicked
		pass
	
	def buttonControlVariables_Clicked( self, event ):
		# TODO: Implement buttonControlVariables_Clicked
		pass
	
	def buttonControlSelfSwitch_Clicked( self, event ):
		# TODO: Implement buttonControlSelfSwitch_Clicked
		pass
	
	def buttonControlTimer_Clicked( self, event ):
		# TODO: Implement buttonControlTimer_Clicked
		pass
	
	def buttonPlayBGM_Clicked( self, event ):
		# TODO: Implement buttonPlayBGM_Clicked
		pass
	
	def buttonFadeOutBGM_Clicked( self, event ):
		# TODO: Implement buttonFadeOutBGM_Clicked
		pass
	
	def buttonPlayBGS_Clicked( self, event ):
		# TODO: Implement buttonPlayBGS_Clicked
		pass
	
	def buttonFadeOutBGS_Clicked( self, event ):
		# TODO: Implement buttonFadeOutBGS_Clicked
		pass
	
	def buttonMemorizeBGMBGS_Clicked( self, event ):
		# TODO: Implement buttonMemorizeBGMBGS_Clicked
		pass
	
	def buttonRestoreBGMBGS_Clicked( self, event ):
		# TODO: Implement buttonRestoreBGMBGS_Clicked
		pass
	
	def buttonPlayME_Clicked( self, event ):
		# TODO: Implement buttonPlayME_Clicked
		pass
	
	def buttonPlaySE_Clicked( self, event ):
		# TODO: Implement buttonPlaySE_Clicked
		pass
	
	def buttonStopSE_Clicked( self, event ):
		# TODO: Implement buttonStopSE_Clicked
		pass
	
	def buttonChangeBattleBGM_Clicked( self, event ):
		# TODO: Implement buttonChangeBattleBGM_Clicked
		pass
	
	def buttonChangeBattleEndME_Clicked( self, event ):
		# TODO: Implement buttonChangeBattleEndME_Clicked
		pass
	
	
