"""Subclass of ForceAction_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ForceAction_Dialog
class ARCedForceAction_Dialog( ARCed_Templates.ForceAction_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ForceAction_Dialog.__init__( self, parent )
	
	# Handlers for ForceAction_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
