"""Subclass of DealDamage_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing DealDamage_Dialog
class ARCedDealDamage_Dialog( ARCed_Templates.DealDamage_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.DealDamage_Dialog.__init__( self, parent )
	
	# Handlers for DealDamage_Dialog events.
	def comboBoxVariable_Clicked( self, event ):
		# TODO: Implement comboBoxVariable_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
