"""Subclass of ShowPicture_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ShowPicture_Dialog
class ARCedShowPicture_Dialog( ARCed_Templates.ShowPicture_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ShowPicture_Dialog.__init__( self, parent )
	
	# Handlers for ShowPicture_Dialog events.
	def comboBoxPictureGraphic_Clicked( self, event ):
		# TODO: Implement comboBoxPictureGraphic_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
