"""Subclass of ChangelGold_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChangelGold_Dialog
class ARCedChangelGold_Dialog( ARCed_Templates.ChangelGold_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChangelGold_Dialog.__init__( self, parent )
	
	# Handlers for ChangelGold_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
