"""Subclass of AnimationTweening_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing AnimationTweening_Dialog
class ARCedAnimationTweening_Dialog( ARCed_Templates.AnimationTweening_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.AnimationTweening_Dialog.__init__( self, parent )
	
	# Handlers for AnimationTweening_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
