"""Subclass of TransferPlayer_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing TransferPlayer_Dialog
class ARCedTransferPlayer_Dialog( ARCed_Templates.TransferPlayer_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.TransferPlayer_Dialog.__init__( self, parent )
	
	# Handlers for TransferPlayer_Dialog events.
	def comboBoxDirectAppointment_Clicked( self, event ):
		# TODO: Implement comboBoxDirectAppointment_Clicked
		pass
	
	def comboBoxVaribleAppointment_Clicked( self, event ):
		# TODO: Implement comboBoxVaribleAppointment_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
