"""Subclass of Enemies_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing Enemies_Panel
class ARCedEnemies_Panel( ARCed_Templates.Enemies_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.Enemies_Panel.__init__( self, parent )
	
	# Handlers for Enemies_Panel events.
	def listBoxEnemies_SelectionChanged( self, event ):
		# TODO: Implement listBoxEnemies_SelectionChanged
		pass
	
	def buttonMaximum_Clicked( self, event ):
		# TODO: Implement buttonMaximum_Clicked
		pass
	
	def textCtrlName_ValueChanged( self, event ):
		# TODO: Implement textCtrlName_ValueChanged
		pass
	
	def bitmapGraphic_DoubleClick( self, event ):
		# TODO: Implement bitmapGraphic_DoubleClick
		pass
	
	def comboBoxAttackAnimation_SelectionChanged( self, event ):
		# TODO: Implement comboBoxAttackAnimation_SelectionChanged
		pass
	
	def spinCtrlExp_ValueChanged( self, event ):
		# TODO: Implement spinCtrlExp_ValueChanged
		pass
	
	def spinCtrlGold_ValueChanged( self, event ):
		# TODO: Implement spinCtrlGold_ValueChanged
		pass
	
	def spinCtrlMaxHP_ValueChanged( self, event ):
		# TODO: Implement spinCtrlMaxHP_ValueChanged
		pass
	
	def spinCtrlStr_ValueChanged( self, event ):
		# TODO: Implement spinCtrlStr_ValueChanged
		pass
	
	def spinCtrlAgi_ValueChanged( self, event ):
		# TODO: Implement spinCtrlAgi_ValueChanged
		pass
	
	def spinCtrlAtk_ValueChanged( self, event ):
		# TODO: Implement spinCtrlAtk_ValueChanged
		pass
	
	def spinCtrlMdef_ValueChanged( self, event ):
		# TODO: Implement spinCtrlMdef_ValueChanged
		pass
	
	def spinCtrlMaxSP_ValueChanged( self, event ):
		# TODO: Implement spinCtrlMaxSP_ValueChanged
		pass
	
	def spinCtrlDex_ValueChanged( self, event ):
		# TODO: Implement spinCtrlDex_ValueChanged
		pass
	
	def spinCtrlInt_ValueChanged( self, event ):
		# TODO: Implement spinCtrlInt_ValueChanged
		pass
	
	def spinCtrlPdef_ValueChanged( self, event ):
		# TODO: Implement spinCtrlPdef_ValueChanged
		pass
	
	def spinCtrlEva_ValueChanged( self, event ):
		# TODO: Implement spinCtrlEva_ValueChanged
		pass
	
	def comboBoxTargetAnimation_ValueChanged( self, event ):
		# TODO: Implement comboBoxTargetAnimation_ValueChanged
		pass
	
	def comboBoxTreasure_ValueChanged( self, event ):
		# TODO: Implement comboBoxTreasure_ValueChanged
		pass
	
	def checkListElements_ValueChanged( self, event ):
		# TODO: Implement checkListElements_ValueChanged
		pass
	
	def checkListStates_ValueChanged( self, event ):
		# TODO: Implement checkListStates_ValueChanged
		pass
	
	def textCtrlNotes_TextChanged( self, event ):
		# TODO: Implement textCtrlNotes_TextChanged
		pass
	
	def listCtrlAction_DoubleClick( self, event ):
		# TODO: Implement listCtrlAction_DoubleClick
		pass
	
	
