"""Subclass of Classes_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing Classes_Panel
class ARCedClasses_Panel( ARCed_Templates.Classes_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.Classes_Panel.__init__( self, parent )
	
	# Handlers for Classes_Panel events.
	def listBoxActors_SelectionChanged( self, event ):
		# TODO: Implement listBoxActors_SelectionChanged
		pass
	
	def buttonMaximum_Clicked( self, event ):
		# TODO: Implement buttonMaximum_Clicked
		pass
	
	def textCtrlName_TextChanged( self, event ):
		# TODO: Implement textCtrlName_TextChanged
		pass
	
	def checkListWeapons_CheckChanged( self, event ):
		# TODO: Implement checkListWeapons_CheckChanged
		pass
	
	def buttonWeaponAll_Clicked( self, event ):
		# TODO: Implement buttonWeaponAll_Clicked
		pass
	
	def buttonWeaponNone_Clicked( self, event ):
		# TODO: Implement buttonWeaponNone_Clicked
		pass
	
	def comboBoxPosition_SelectionChanged( self, event ):
		# TODO: Implement comboBoxPosition_SelectionChanged
		pass
	
	def checkListArmors_CheckChanged( self, event ):
		# TODO: Implement checkListArmors_CheckChanged
		pass
	
	def buttonArmorAll_Clicked( self, event ):
		# TODO: Implement buttonArmorAll_Clicked
		pass
	
	def buttonArmorNone_Clicked( self, event ):
		# TODO: Implement buttonArmorNone_Clicked
		pass
	
	def checkListElements_CheckChanged( self, event ):
		# TODO: Implement checkListElements_CheckChanged
		pass
	
	def checkListStates_ChceckChanged( self, event ):
		# TODO: Implement checkListStates_ChceckChanged
		pass
	
	def listBoxSkills_DoubleClick( self, event ):
		# TODO: Implement listBoxSkills_DoubleClick
		pass
	
	
