"""Subclass of ConditionalBranch_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ConditionalBranch_Dialog
class ARCedConditionalBranch_Dialog( ARCed_Templates.ConditionalBranch_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ConditionalBranch_Dialog.__init__( self, parent )
	
	# Handlers for ConditionalBranch_Dialog events.
	def radioButtonActor_CheckChanged( self, event ):
		# TODO: Implement radioButtonActor_CheckChanged
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
