"""Subclass of ShopGoods_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ShopGoods_Dialog
class ARCedShopGoods_Dialog( ARCed_Templates.ShopGoods_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ShopGoods_Dialog.__init__( self, parent )
	
	# Handlers for ShopGoods_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
