"""Subclass of AnimationCellBatch_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing AnimationCellBatch_Dialog
class ARCedAnimationCellBatch_Dialog( ARCed_Templates.AnimationCellBatch_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.AnimationCellBatch_Dialog.__init__( self, parent )
	
	# Handlers for AnimationCellBatch_Dialog events.
	def checkBoxPattern_CheckChanged( self, event ):
		# TODO: Implement checkBoxPattern_CheckChanged
		pass
	
	def checkBoxAngle_CheckChanged( self, event ):
		# TODO: Implement checkBoxAngle_CheckChanged
		pass
	
	def checkBoxX_CheckChanged( self, event ):
		# TODO: Implement checkBoxX_CheckChanged
		pass
	
	def checkBoxFlip_CheckChanged( self, event ):
		# TODO: Implement checkBoxFlip_CheckChanged
		pass
	
	def checkBoxY_CheckChanged( self, event ):
		# TODO: Implement checkBoxY_CheckChanged
		pass
	
	def checkBoxOpacity_CheckChanged( self, event ):
		# TODO: Implement checkBoxOpacity_CheckChanged
		pass
	
	def checkBoxZoom_CheckChanged( self, event ):
		# TODO: Implement checkBoxZoom_CheckChanged
		pass
	
	def checkBoxBlending_CheckChanged( self, event ):
		# TODO: Implement checkBoxBlending_CheckChanged
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
