"""Subclass of ScriptCall_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ScriptCall_Dialog
class ARCedScriptCall_Dialog( ARCed_Templates.ScriptCall_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ScriptCall_Dialog.__init__( self, parent )
	
	# Handlers for ScriptCall_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
