"""Subclass of DatabaseMain_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing DatabaseMain_Panel
class ARCedDatabaseMain_Panel( ARCed_Templates.DatabaseMain_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.DatabaseMain_Panel.__init__( self, parent )
	
	# Handlers for DatabaseMain_Panel events.
	def buttonMainOK_Clicked( self, event ):
		# TODO: Implement buttonMainOK_Clicked
		pass
	
	def buttonMainCancel_Clicked( self, event ):
		# TODO: Implement buttonMainCancel_Clicked
		pass
	
	def buttonMainApply_Clicked( self, event ):
		# TODO: Implement buttonMainApply_Clicked
		pass
	
	
