"""Subclass of AnimationEntireSlide_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing AnimationEntireSlide_Dialog
class ARCedAnimationEntireSlide_Dialog( ARCed_Templates.AnimationEntireSlide_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.AnimationEntireSlide_Dialog.__init__( self, parent )
	
	# Handlers for AnimationEntireSlide_Dialog events.
	def buttonOK_Click( self, event ):
		# TODO: Implement buttonOK_Click
		pass
	
	def buttonCancel_Click( self, event ):
		# TODO: Implement buttonCancel_Click
		pass
	
	
