"""Subclass of DatabaseMain_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing DatabaseMain_Panel
class ARCedDatabaseMain_Panel( ARCed_Templates.DatabaseMain_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.DatabaseMain_Panel.__init__( self, parent )
	
	# Handlers for DatabaseMain_Panel events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel( self, event ):
		# TODO: Implement buttonCancel
		pass
	
	
