"""Subclass of Skills_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing Skills_Panel
class ARCedSkills_Panel( ARCed_Templates.Skills_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.Skills_Panel.__init__( self, parent )
	
	# Handlers for Skills_Panel events.
	def listBoxSkills_SelectionChanged( self, event ):
		# TODO: Implement listBoxSkills_SelectionChanged
		pass
	
	def buttonMaximum_Clicked( self, event ):
		# TODO: Implement buttonMaximum_Clicked
		pass
	
	def textCtrlName_TextChanged( self, event ):
		# TODO: Implement textCtrlName_TextChanged
		pass
	
	def comboBoxIcon_SelectionChanged( self, event ):
		# TODO: Implement comboBoxIcon_SelectionChanged
		pass
	
	def textCtrlDescription_TextChange( self, event ):
		# TODO: Implement textCtrlDescription_TextChange
		pass
	
	def comboBoxScope_SelectionChanged( self, event ):
		# TODO: Implement comboBoxScope_SelectionChanged
		pass
	
	def comboBoxUserAnimation_SelectionChanged( self, event ):
		# TODO: Implement comboBoxUserAnimation_SelectionChanged
		pass
	
	def comboBoxMenuSE_Clicked( self, event ):
		# TODO: Implement comboBoxMenuSE_Clicked
		pass
	
	def comboBoxOccasion_SelectionChanged( self, event ):
		# TODO: Implement comboBoxOccasion_SelectionChanged
		pass
	
	def comboBoxTargetAnimation_SelectionChanged( self, event ):
		# TODO: Implement comboBoxTargetAnimation_SelectionChanged
		pass
	
	def comboBoxCommonEvent_SelectionChanged( self, event ):
		# TODO: Implement comboBoxCommonEvent_SelectionChanged
		pass
	
	def spinCtrlSPCost_ValueChanged( self, event ):
		# TODO: Implement spinCtrlSPCost_ValueChanged
		pass
	
	def spinCtrlStrF_ValueChanged( self, event ):
		# TODO: Implement spinCtrlStrF_ValueChanged
		pass
	
	def spinCtrlHitRate_ValueChanged( self, event ):
		# TODO: Implement spinCtrlHitRate_ValueChanged
		pass
	
	def spinCtrlPower_ValueChanged( self, event ):
		# TODO: Implement spinCtrlPower_ValueChanged
		pass
	
	def spinCtrlDexF_ValueChanged( self, event ):
		# TODO: Implement spinCtrlDexF_ValueChanged
		pass
	
	def spinCtrlPDEF_ValueChanged( self, event ):
		# TODO: Implement spinCtrlPDEF_ValueChanged
		pass
	
	def spinCtrlAtkF_ValueChanged( self, event ):
		# TODO: Implement spinCtrlAtkF_ValueChanged
		pass
	
	def spinCtrlAgiF_ValueChanged( self, event ):
		# TODO: Implement spinCtrlAgiF_ValueChanged
		pass
	
	def spinCtrlMDEF_ValueChanged( self, event ):
		# TODO: Implement spinCtrlMDEF_ValueChanged
		pass
	
	def spinCtrlEvaF_ValueChanged( self, event ):
		# TODO: Implement spinCtrlEvaF_ValueChanged
		pass
	
	def spinCtrlIntF_ValueChanged( self, event ):
		# TODO: Implement spinCtrlIntF_ValueChanged
		pass
	
	def spinCtrlVariance_ValueChanged( self, event ):
		# TODO: Implement spinCtrlVariance_ValueChanged
		pass
	
	def checkListElements_CheckChanged( self, event ):
		# TODO: Implement checkListElements_CheckChanged
		pass
	
	def checkListStates_CheckChanged( self, event ):
		# TODO: Implement checkListStates_CheckChanged
		pass
	
	def textCtrlNotes_TextChanged( self, event ):
		# TODO: Implement textCtrlNotes_TextChanged
		pass
	
	
