"""Subclass of Items_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing Items_Panel
class ARCedItems_Panel( ARCed_Templates.Items_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.Items_Panel.__init__( self, parent )
	
	# Handlers for Items_Panel events.
	def listBoxItems_SelectionChanged( self, event ):
		# TODO: Implement listBoxItems_SelectionChanged
		pass
	
	def buttonMaximum_Clicked( self, event ):
		# TODO: Implement buttonMaximum_Clicked
		pass
	
	def textCtrlName_TextChanged( self, event ):
		# TODO: Implement textCtrlName_TextChanged
		pass
	
	def comboBoxIcon_SelectionChanged( self, event ):
		# TODO: Implement comboBoxIcon_SelectionChanged
		pass
	
	def textCtrlDescription_TextChange( self, event ):
		# TODO: Implement textCtrlDescription_TextChange
		pass
	
	def comboBoxScope_SelectionChanged( self, event ):
		# TODO: Implement comboBoxScope_SelectionChanged
		pass
	
	def comboBoxUserAnimation_SelectionChanged( self, event ):
		# TODO: Implement comboBoxUserAnimation_SelectionChanged
		pass
	
	def comboBoxMenuSE_SelectionChanged( self, event ):
		# TODO: Implement comboBoxMenuSE_SelectionChanged
		pass
	
	def comboBoxOccasion_SelectionChanged( self, event ):
		# TODO: Implement comboBoxOccasion_SelectionChanged
		pass
	
	def comboBoxTargetAnimation_SelectionChanged( self, event ):
		# TODO: Implement comboBoxTargetAnimation_SelectionChanged
		pass
	
	def comboBoxCommonEvent_SelectionChanged( self, event ):
		# TODO: Implement comboBoxCommonEvent_SelectionChanged
		pass
	
	def spinCtrlPrice_ValueChanged( self, event ):
		# TODO: Implement spinCtrlPrice_ValueChanged
		pass
	
	def spinCtrlRecrHPPercent_ValueChanged( self, event ):
		# TODO: Implement spinCtrlRecrHPPercent_ValueChanged
		pass
	
	def spinCtrlHitRate_ValueChanged( self, event ):
		# TODO: Implement spinCtrlHitRate_ValueChanged
		pass
	
	def comboBoxConsumable_SelectionChanged( self, event ):
		# TODO: Implement comboBoxConsumable_SelectionChanged
		pass
	
	def spinCtrlRecrHP_ValueChanged( self, event ):
		# TODO: Implement spinCtrlRecrHP_ValueChanged
		pass
	
	def spinCtrlPDEF_ValueChanged( self, event ):
		# TODO: Implement spinCtrlPDEF_ValueChanged
		pass
	
	def comboBoxParameter_SelectionChanged( self, event ):
		# TODO: Implement comboBoxParameter_SelectionChanged
		pass
	
	def spinCtrlRecrSPPercent_ValueChanged( self, event ):
		# TODO: Implement spinCtrlRecrSPPercent_ValueChanged
		pass
	
	def spinCtrlMDEF_ValueChanged( self, event ):
		# TODO: Implement spinCtrlMDEF_ValueChanged
		pass
	
	def spinCtrlParameterInc_ValueChanged( self, event ):
		# TODO: Implement spinCtrlParameterInc_ValueChanged
		pass
	
	def spinCtrlRecrSP_ValueChanged( self, event ):
		# TODO: Implement spinCtrlRecrSP_ValueChanged
		pass
	
	def spinCtrlVariance_ValueChanged( self, event ):
		# TODO: Implement spinCtrlVariance_ValueChanged
		pass
	
	def checkListElements_CheckChanged( self, event ):
		# TODO: Implement checkListElements_CheckChanged
		pass
	
	def checkListStates_CheckChanged( self, event ):
		# TODO: Implement checkListStates_CheckChanged
		pass
	
	def textCtrlNotes_TextChanged( self, event ):
		# TODO: Implement textCtrlNotes_TextChanged
		pass
	
	
