"""Subclass of ChooseGraphic_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChooseGraphic_Dialog
class ARCedChooseGraphic_Dialog( ARCed_Templates.ChooseGraphic_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChooseGraphic_Dialog.__init__( self, parent )
	
	# Handlers for ChooseGraphic_Dialog events.
	def listBoxGraphics_SelectionChanged( self, event ):
		# TODO: Implement listBoxGraphics_SelectionChanged
		pass
	
	def sliderHue_Scrolled( self, event ):
		# TODO: Implement sliderHue_Scrolled
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
