"""Subclass of ChangeHP_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChangeHP_Dialog
class ARCedChangeHP_Dialog( ARCed_Templates.ChangeHP_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChangeHP_Dialog.__init__( self, parent )
	
	# Handlers for ChangeHP_Dialog events.
	def comboBoxVariable_Clicked( self, event ):
		# TODO: Implement comboBoxVariable_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
