"""Subclass of Skill_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing Skill_Dialog
class ARCedSkill_Dialog( ARCed_Templates.Skill_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.Skill_Dialog.__init__( self, parent )
	
