"""Subclass of CallCommonEvent_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing CallCommonEvent_Dialog
class ARCedCallCommonEvent_Dialog( ARCed_Templates.CallCommonEvent_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.CallCommonEvent_Dialog.__init__( self, parent )
	
	# Handlers for CallCommonEvent_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
