"""Subclass of ChangeMaximum_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChangeMaximum_Dialog
class ARCedChangeMaximum_Dialog( ARCed_Templates.ChangeMaximum_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChangeMaximum_Dialog.__init__( self, parent )
	
	# Handlers for ChangeMaximum_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
