"""Subclass of ExpCurve_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ExpCurve_Dialog
class ARCedExpCurve_Dialog( ARCed_Templates.ExpCurve_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ExpCurve_Dialog.__init__( self, parent )
	
	# Handlers for ExpCurve_Dialog events.
	def sliderBasis_Scrolled( self, event ):
		# TODO: Implement sliderBasis_Scrolled
		pass
	
	def spinCtrlBasis__ValueChanged( self, event ):
		# TODO: Implement spinCtrlBasis__ValueChanged
		pass
	
	def sliderInflation_Scrolled( self, event ):
		# TODO: Implement sliderInflation_Scrolled
		pass
	
	def spinCtrlInflation_ValueChanged( self, event ):
		# TODO: Implement spinCtrlInflation_ValueChanged
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
