"""Subclass of GenerateCurve_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing GenerateCurve_Dialog
class ARCedGenerateCurve_Dialog( ARCed_Templates.GenerateCurve_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.GenerateCurve_Dialog.__init__( self, parent )
	
	# Handlers for GenerateCurve_Dialog events.
	def spinCtrlMaxLevel_ValueChanged( self, event ):
		# TODO: Implement spinCtrlMaxLevel_ValueChanged
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	def sliderCurve_Scrolled( self, event ):
		# TODO: Implement sliderCurve_Scrolled
		pass
	
	
