"""Subclass of Classes_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing Classes_Panel
class ARCedClasses_Panel( ARCed_Templates.Classes_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.Classes_Panel.__init__( self, parent )
	
	# Handlers for Classes_Panel events.
	def listBoxActors_SelectionChanged( self, event ):
		# TODO: Implement listBoxActors_SelectionChanged
		pass
	
	def buttonMaximum_Clicked( self, event ):
		# TODO: Implement buttonMaximum_Clicked
		pass
	
	
