"""Subclass of RecoverAll_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing RecoverAll_Dialog
class ARCedRecoverAll_Dialog( ARCed_Templates.RecoverAll_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.RecoverAll_Dialog.__init__( self, parent )
	
	# Handlers for RecoverAll_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
