"""Subclass of ControlVariables_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ControlVariables_Dialog
class ARCedControlVariables_Dialog( ARCed_Templates.ControlVariables_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ControlVariables_Dialog.__init__( self, parent )
	
	# Handlers for ControlVariables_Dialog events.
	def spinCtrlBatchStart_ValueChanged( self, event ):
		# TODO: Implement spinCtrlBatchStart_ValueChanged
		pass
	
	def spinCtrlBatchEnd_ValueChanged( self, event ):
		# TODO: Implement spinCtrlBatchEnd_ValueChanged
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
