"""Subclass of Actors_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing Actors_Panel
class ARCedActors_Panel( ARCed_Templates.Actors_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.Actors_Panel.__init__( self, parent )
	
	# Handlers for Actors_Panel events.
	def listBoxActors_SelectionChanged( self, event ):
		# TODO: Implement listBoxActors_SelectionChanged
		pass
	
	def buttonMaximum_Clicked( self, event ):
		# TODO: Implement buttonMaximum_Clicked
		pass
	
	def textBoxName_TextChanged( self, event ):
		# TODO: Implement textBoxName_TextChanged
		pass
	
	def comboBoxClass_SelectionChanged( self, event ):
		# TODO: Implement comboBoxClass_SelectionChanged
		pass
	
	def spinCtrlInitialLevel_ValueChanged( self, event ):
		# TODO: Implement spinCtrlInitialLevel_ValueChanged
		pass
	
	def spinCtrlFinalLevel_ValueChanged( self, event ):
		# TODO: Implement spinCtrlFinalLevel_ValueChanged
		pass
	
	def comboBoxExperience_Click( self, event ):
		# TODO: Implement comboBoxExperience_Click
		pass
	
	def bitmapCharacterGraphic_Click( self, event ):
		# TODO: Implement bitmapCharacterGraphic_Click
		pass
	
	def bitmapBattlerGraphic_Click( self, event ):
		# TODO: Implement bitmapBattlerGraphic_Click
		pass
	
	def bitmapMaxHP_Click( self, event ):
		# TODO: Implement bitmapMaxHP_Click
		pass
	
	def bitmapStr_Click( self, event ):
		# TODO: Implement bitmapStr_Click
		pass
	
	def bitmapAgi_Click( self, event ):
		# TODO: Implement bitmapAgi_Click
		pass
	
	def bitmapMaxSP_Click( self, event ):
		# TODO: Implement bitmapMaxSP_Click
		pass
	
	def bitmapDex_Click( self, event ):
		# TODO: Implement bitmapDex_Click
		pass
	
	def bitmapInt_Click( self, event ):
		# TODO: Implement bitmapInt_Click
		pass
	
	def comboBoxWeapon_SelectionChanged( self, event ):
		# TODO: Implement comboBoxWeapon_SelectionChanged
		pass
	
	def comboBoxShield_SelectionChanged( self, event ):
		# TODO: Implement comboBoxShield_SelectionChanged
		pass
	
	def comboBoxHelmet_SelectionChanged( self, event ):
		# TODO: Implement comboBoxHelmet_SelectionChanged
		pass
	
	def comboBoxBodyArmor( self, event ):
		# TODO: Implement comboBoxBodyArmor
		pass
	
	def comboBoxAccessory_SelectionChanged( self, event ):
		# TODO: Implement comboBoxAccessory_SelectionChanged
		pass
	
	def checkBoxWeapon_CheckChanged( self, event ):
		# TODO: Implement checkBoxWeapon_CheckChanged
		pass
	
	def checkBoxShield_CheckChanged( self, event ):
		# TODO: Implement checkBoxShield_CheckChanged
		pass
	
	def checkBoxHelmet_CheckChanged( self, event ):
		# TODO: Implement checkBoxHelmet_CheckChanged
		pass
	
	def checkBoxBodyArmor_CheckChanged( self, event ):
		# TODO: Implement checkBoxBodyArmor_CheckChanged
		pass
	
	def checkBoxAccessory_CheckChanged( self, event ):
		# TODO: Implement checkBoxAccessory_CheckChanged
		pass
	
	
