"""Subclass of EventCommands2_Panel, which is generated by wxFormBuilder."""

import wx
from Core.Database import ARCed_Templates as Templates

# Implementing EventCommands2_Panel
class EventCommands2_Panel( Templates.EventCommands2_Panel ):
    def __init__( self, parent ):
        Templates.EventCommands2_Panel.__init__( self, parent )
    
    # Handlers for EventCommands2_Panel events.
    def buttonTransferPlayer_Clicked( self, event ):
        # TODO: Implement buttonTransferPlayer_Clicked
        pass
    
    def buttonSetMoveRoute_Clicked( self, event ):
        # TODO: Implement buttonSetMoveRoute_Clicked
        pass
    
    def buttonSetEventLocation_Clicked( self, event ):
        # TODO: Implement buttonSetEventLocation_Clicked
        pass
    
    def buttonScrollMap_Clicked( self, event ):
        # TODO: Implement buttonScrollMap_Clicked
        pass
    
    def buttonWaitForMovesCompletion_Clicked( self, event ):
        # TODO: Implement buttonWaitForMovesCompletion_Clicked
        pass
    
    def buttonPrepareForTransition_Clicked( self, event ):
        # TODO: Implement buttonPrepareForTransition_Clicked
        pass
    
    def buttonExecuteTransition_Clicked( self, event ):
        # TODO: Implement buttonExecuteTransition_Clicked
        pass
    
    def buttonChangeScreenTone_Clicked( self, event ):
        # TODO: Implement buttonChangeScreenTone_Clicked
        pass
    
    def buttonScreenFlash_Clicked( self, event ):
        # TODO: Implement buttonScreenFlash_Clicked
        pass
    
    def buttonScreenShake_Clicked( self, event ):
        # TODO: Implement buttonScreenShake_Clicked
        pass
    
    def buttonChangePartyMember_Clicked( self, event ):
        # TODO: Implement buttonChangePartyMember_Clicked
        pass
    
    def buttonChangeGold_Clicked( self, event ):
        # TODO: Implement buttonChangeGold_Clicked
        pass
    
    def buttonChangeItem_Clicked( self, event ):
        # TODO: Implement buttonChangeItem_Clicked
        pass
    
    def buttonChangeWeapon_Clicked( self, event ):
        # TODO: Implement buttonChangeWeapon_Clicked
        pass
    
    def buttonArmor_Clicked( self, event ):
        # TODO: Implement buttonArmor_Clicked
        pass
    
    def buttonChangeMapSettings_Clicked( self, event ):
        # TODO: Implement buttonChangeMapSettings_Clicked
        pass
    
    def buttonSetWeatherEffects_Clicked( self, event ):
        # TODO: Implement buttonSetWeatherEffects_Clicked
        pass
    
    def buttonChangeFogColorTone_Clicked( self, event ):
        # TODO: Implement buttonChangeFogColorTone_Clicked
        pass
    
    def buttonChangeFogOpacity_Clicked( self, event ):
        # TODO: Implement buttonChangeFogOpacity_Clicked
        pass
    
    def buttonChangeEncounter_Clicked( self, event ):
        # TODO: Implement buttonChangeEncounter_Clicked
        pass
    
    def buttonBattleProcessing_Clicked( self, event ):
        # TODO: Implement buttonBattleProcessing_Clicked
        pass
    
    def buttonShopProcessing_Clicked( self, event ):
        # TODO: Implement buttonShopProcessing_Clicked
        pass
    
    def buttonNameInputProcessing_Clicked( self, event ):
        # TODO: Implement buttonNameInputProcessing_Clicked
        pass
    
    def buttonButtonInputProcessing_Clicked( self, event ):
        # TODO: Implement buttonButtonInputProcessing_Clicked
        pass
    
    def buttonGameOver_Clicked( self, event ):
        # TODO: Implement buttonGameOver_Clicked
        pass
    
    def buttonReturnToTitleScreen_Clicked( self, event ):
        # TODO: Implement buttonReturnToTitleScreen_Clicked
        pass
    
    def buttonChangeMenuAccess_Clicked( self, event ):
        # TODO: Implement buttonChangeMenuAccess_Clicked
        pass
    
    def buttonChangeSaveAccess_Clicked( self, event ):
        # TODO: Implement buttonChangeSaveAccess_Clicked
        pass
    
    def buttonCallMenuScreen_Clicked( self, event ):
        # TODO: Implement buttonCallMenuScreen_Clicked
        pass
    
    def buttonCallSaveScreen_Clicked( self, event ):
        # TODO: Implement buttonCallSaveScreen_Clicked
        pass
    
    
