"""Subclass of ButonProcessing_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing ButonProcessing_Dialog
class ButonProcessing_Dialog( Templates.ButtonProcessing_Dialog ):
	def __init__( self, parent ):
		Templates.ButonProcessing_Dialog.__init__( self, parent )
	
	# Handlers for ButonProcessing_Dialog events.
	def comboBoxVariable_Clicked( self, event ):
		# TODO: Implement comboBoxVariable_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
