"""Subclass of ChangeActorClass_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing ChangeActorClass_Dialog
class ChangeActorClass_Dialog( Templates.ChangeActorClass_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChangeActorClass_Dialog.__init__( self, parent )
	
	# Handlers for ChangeActorClass_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
