"""Subclass of ChangeActorName_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChangeActorName_Dialog
class ChangeActorName_Dialog(ARCed_Templates.ChangeActorName_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChangeActorName_Dialog.__init__( self, parent )
	
	# Handlers for ChangeActorName_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
