"""Subclass of ChangeActorGraphic_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing ChangeActorGraphic_Dialog
class ChangeActorGraphic_Dialog( Templates.ChangeActorGraphic_Dialog ):
	def __init__( self, parent ):
		Templates.ChangeActorGraphic_Dialog.__init__( self, parent )
	
	# Handlers for ChangeActorGraphic_Dialog events.
	def comboBoxCharacter_Clicked( self, event ):
		# TODO: Implement comboBoxCharacter_Clicked
		pass
	
	def comboBoxBattler_Clicked( self, event ):
		# TODO: Implement comboBoxBattler_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
