"""Subclass of Jump_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing Jump_Dialog
class Jump_Dialog( Templates.Jump_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.Jump_Dialog.__init__( self, parent )
	
	# Handlers for Jump_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
