"""Subclass of RotatePicture_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing RotatePicture_Dialog
class RotatePicture_Dialog( Templates.RotatePicture_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.RotatePicture_Dialog.__init__( self, parent )
	
	# Handlers for RotatePicture_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
