"""Subclass of ScrollMap_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing ScrollMap_Dialog
class ScrollMap_Dialog( Templates.ScrollMap_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ScrollMap_Dialog.__init__( self, parent )
	
	# Handlers for ScrollMap_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
