"""Subclass of SetEventLocation_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing SetEventLocation_Dialog
class SetEventLocation_Dialog( Templates.SetEventLocation_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.SetEventLocation_Dialog.__init__( self, parent )
	
	# Handlers for SetEventLocation_Dialog events.
	def radioButtonDirect_CheckChanged( self, event ):
		# TODO: Implement radioButtonDirect_CheckChanged
		pass
	
	def comboBoxDirectAppointment_Clicked( self, event ):
		# TODO: Implement comboBoxDirectAppointment_Clicked
		pass
	
	def radioButtonVariable_CheckChanged( self, event ):
		# TODO: Implement radioButtonVariable_CheckChanged
		pass
	
	def comboBoxMapID_Clicked( self, event ):
		# TODO: Implement comboBoxMapID_Clicked
		pass
	
	def comboBoxMapX_Clicked( self, event ):
		# TODO: Implement comboBoxMapX_Clicked
		pass
	
	def comboBoxMapY_Clicked( self, event ):
		# TODO: Implement comboBoxMapY_Clicked
		pass
	
	def radioButtonExchange_CheckChanged( self, event ):
		# TODO: Implement radioButtonExchange_CheckChanged
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
