"""Subclass of TransparentFlag_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing TransparentFlag_Dialog
class TransparentFlag_Dialog( Templates.TransparentFlag_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.TransparentFlag_Dialog.__init__( self, parent )
	
	# Handlers for TransparentFlag_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
