"""Subclass of Wait_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing Wait_Dialog
class Wait_Dialog( Templates.Wait_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.Wait_Dialog.__init__( self, parent )
	
	# Handlers for Wait_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
