"""Subclass of ChangeSpeed_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing ChangeSpeed_Dialog
class ChangeSpeed_Dialog( Templates.ChangeSpeed_Dialog ):
	def __init__( self, parent ):
		Templates.ChangeSpeed_Dialog.__init__( self, parent )
	
	# Handlers for ChangeSpeed_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
