"""Subclass of ChangeAccess_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing ChangeAccess_Dialog
class ChangeAccess_Dialog( Templates.ChangeAccess_Dialog ):
	def __init__( self, parent ):
		Templates.ChangeAccess_Dialog.__init__( self, parent )
	
	# Handlers for ChangeAccess_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
