"""Subclass of ControlSelfSwitches_Dialog, which is generated by wxFormBuilder."""

import wx
from Core.Database import ARCed_Templates as Templates

# Implementing ControlSelfSwitches_Dialog
class ControlSelfSwitches_Dialog( Templates.ControlSelfSwitches_Dialog ):
	def __init__( self, parent ):
		Templates.ControlSelfSwitches_Dialog.__init__( self, parent )
	
	# Handlers for ControlSelfSwitches_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
