"""Subclass of ChangeTextOptions_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChangeTextOptions_Dialog
class ARCedChangeTextOptions_Dialog( ARCed_Templates.ChangeTextOptions_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChangeTextOptions_Dialog.__init__( self, parent )
	
	# Handlers for ChangeTextOptions_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
