"""Subclass of FadeOutAudio_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing FadeOutAudio_Dialog
class ARCedFadeOutAudio_Dialog( ARCed_Templates.FadeOutAudio_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.FadeOutAudio_Dialog.__init__( self, parent )
	
	# Handlers for FadeOutAudio_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
