"""Subclass of ChangeParameters_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChangeParameters_Dialog
class ARCedChangeParameters_Dialog( ARCed_Templates.ChangeParameters_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChangeParameters_Dialog.__init__( self, parent )
	
	# Handlers for ChangeParameters_Dialog events.
	def radioButtonConstant_CheckChanged( self, event ):
		# TODO: Implement radioButtonConstant_CheckChanged
		pass
	
	def radioButtonVariable_CheckChanged( self, event ):
		# TODO: Implement radioButtonVariable_CheckChanged
		pass
	
	def comboBoxVariable_Clicked( self, event ):
		# TODO: Implement comboBoxVariable_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
