"""Subclass of ParameterGraph_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ParameterGraph_Panel
class ARCedParameterGraph_Panel( ARCed_Templates.ParameterGraph_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.ParameterGraph_Panel.__init__( self, parent )
	
	# Handlers for ParameterGraph_Panel events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
