"""Subclass of Parameter_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing Parameter_Panel
class ARCedParameter_Panel( ARCed_Templates.Parameter_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.Parameter_Panel.__init__( self, parent )
	
	def buttonAddParameter_Clicked( self, event ):
		# TODO: Implement buttonAddParameter_Clicked
		pass
	
	def buttonRemoveParameter_Clicked( self, event ):
		# TODO: Implement buttonRemoveParameter_Clicked
		pass
	
	def buttonGenerateCurve_Clicked( self, event ):
		# TODO: Implement buttonGenerateCurve_Clicked
		pass
	
	
