"""Subclass of InputNumber_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing InputNumber_Dialog
class InputNumber_Dialog(ARCed_Templates.InputNumber_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.InputNumber_Dialog.__init__( self, parent )
	
	# Handlers for InputNumber_Dialog events.
	def comboBoxVariable_Clicked( self, event ):
		# TODO: Implement comboBoxVariable_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
