"""Subclass of AnimationEntireSlide_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing AnimationEntireSlide_Dialog
class AnimationEntireSlide_Dialog(ARCed_Templates.AnimationEntireSlide_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.AnimationEntireSlide_Dialog.__init__( self, parent )
	
	# Handlers for AnimationEntireSlide_Dialog events.
	def spinCtrlFramesStart_ValueChanged( self, event ):
		# TODO: Implement spinCtrlFramesStart_ValueChanged
		pass
	
	def spinCtrlFramesEnd_ValueChanged( self, event ):
		# TODO: Implement spinCtrlFramesEnd_ValueChanged
		pass
	
	def buttonOK_Click( self, event ):
		# TODO: Implement buttonOK_Click
		pass
	
	def buttonCancel_Click( self, event ):
		# TODO: Implement buttonCancel_Click
		pass
	
	
