"""Subclass of ChangePartyMember_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChangePartyMember_Dialog
class ChangePartyMember_Dialog(ARCed_Templates.ChangePartyMember_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChangePartyMember_Dialog.__init__( self, parent )
	
	# Handlers for ChangePartyMember_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
