"""Subclass of ChangeBlending_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChangeBlending_Dialog
class ChangeBlending_Dialog(ARCed_Templates.ChangeBlending_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChangeBlending_Dialog.__init__( self, parent )
	
	# Handlers for ChangeBlending_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
