"""Subclass of ChooseFogGraphic_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing ChooseFogGraphic_Dialog
class ChooseFogGraphic_Dialog( Templates.ChooseFogGraphic_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChooseFogGraphic_Dialog.__init__( self, parent )
	
	# Handlers for ChooseFogGraphic_Dialog events.
	def listBoxGraphics_SelectionChanged( self, event ):
		# TODO: Implement listBoxGraphics_SelectionChanged
		pass
	
	def spinCtrOpacityl_ValueChanged( self, event ):
		# TODO: Implement spinCtrOpacityl_ValueChanged
		pass
	
	def comboBoxBlending_SelectionChanged( self, event ):
		# TODO: Implement comboBoxBlending_SelectionChanged
		pass
	
	def spinCtrlZoom_ValueChanged( self, event ):
		# TODO: Implement spinCtrlZoom_ValueChanged
		pass
	
	def spinCtrlSX_ValueChanged( self, event ):
		# TODO: Implement spinCtrlSX_ValueChanged
		pass
	
	def spinCtrlSY_ValueChanged( self, event ):
		# TODO: Implement spinCtrlSY_ValueChanged
		pass
	
	def sliderHue_Scrolled( self, event ):
		# TODO: Implement sliderHue_Scrolled
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
