"""Subclass of EnemyAppearance_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing EnemyAppearance_Dialog
class EnemyAppearance_Dialog( Templates.EnemyAppearance_Dialog ):
	def __init__( self, parent ):
		Templates.EnemyAppearance_Dialog.__init__( self, parent )
	
	# Handlers for EnemyAppearance_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
