"""Subclass of ScriptCall_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing ScriptCall_Dialog
class ScriptCall_Dialog( Templates.ScriptCall_Dialog ):
	def __init__( self, parent ):
		Templates.ScriptCall_Dialog.__init__( self, parent )
	
	# Handlers for ScriptCall_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
