"""Subclass of ScriptSettings_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ScriptSettings_Dialog
class ScriptSettings_Dialog( ARCed_Templates.ScriptSettings_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ScriptSettings_Dialog.__init__( self, parent )
	
	# Handlers for ScriptSettings_Dialog events.
	def noteBookSettings_PageChanged( self, event ):
		# TODO: Implement noteBookSettings_PageChanged
		pass
	
	def comboBoxFont_SelectionChanged( self, event ):
		# TODO: Implement comboBoxFont_SelectionChanged
		pass
	
	def comboBoxSize_SelectionChanged( self, event ):
		# TODO: Implement comboBoxSize_SelectionChanged
		pass
	
	def listBoxDisplayItems_SelectionChanged( self, event ):
		# TODO: Implement listBoxDisplayItems_SelectionChanged
		pass
	
	def textCtrlForeColor_TextChanged( self, event ):
		# TODO: Implement textCtrlForeColor_TextChanged
		pass
	
	def buttonForeColor_Clicked( self, event ):
		# TODO: Implement buttonForeColor_Clicked
		pass
	
	def textCtrlBackColor_TextChanged( self, event ):
		# TODO: Implement textCtrlBackColor_TextChanged
		pass
	
	def buttonBackColor_Clicked( self, event ):
		# TODO: Implement buttonBackColor_Clicked
		pass
	
	def checkBoxBold_CheckChanged( self, event ):
		# TODO: Implement checkBoxBold_CheckChanged
		pass
	
	def checkBoxItalic_CheckChanged( self, event ):
		# TODO: Implement checkBoxItalic_CheckChanged
		pass
	
	def spinCtrlTabWidth_ValueChanged( self, event ):
		# TODO: Implement spinCtrlTabWidth_ValueChanged
		pass
	
	def spinCtrlEdgeColumn_ValueChanged( self, event ):
		# TODO: Implement spinCtrlEdgeColumn_ValueChanged
		pass
	
	def checkBoxIndentGuide_CheckChanged( self, event ):
		# TODO: Implement checkBoxIndentGuide_CheckChanged
		pass
	
	def checkBoxCaret_CheckChanged( self, event ):
		# TODO: Implement checkBoxCaret_CheckChanged
		pass
	
	def textCtrlCaretColor_TextChanged( self, event ):
		# TODO: Implement textCtrlCaretColor_TextChanged
		pass
	
	def buttonCaretColor_Clicked( self, event ):
		# TODO: Implement buttonCaretColor_Clicked
		pass
	
	def spinCtrlCaretAlpha_ValueChanged( self, event ):
		# TODO: Implement spinCtrlCaretAlpha_ValueChanged
		pass
	
	
