"""Subclass of ShowPicture_Dialog, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing ShowPicture_Dialog
class ShowPicture_Dialog( Templates.ShowPicture_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ShowPicture_Dialog.__init__( self, parent )
	
	# Handlers for ShowPicture_Dialog events.
	def comboBoxPictureGraphic_Clicked( self, event ):
		# TODO: Implement comboBoxPictureGraphic_Clicked
		pass
	
	def radioButtonConstant_CheckChanged( self, event ):
		# TODO: Implement radioButtonConstant_CheckChanged
		pass
	
	def radioButtonVariable_CheckChanged( self, event ):
		# TODO: Implement radioButtonVariable_CheckChanged
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
