"""Subclass of DealDamage_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing DealDamage_Dialog
class ARCedDealDamage_Dialog( ARCed_Templates.DealDamage_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.DealDamage_Dialog.__init__( self, parent )
	
	# Handlers for DealDamage_Dialog events.
	def radioButtonEnemy_CheckChanged( self, event ):
		# TODO: Implement radioButtonEnemy_CheckChanged
		pass
	
	def radioButtonActor_CheckChanged( self, event ):
		# TODO: Implement radioButtonActor_CheckChanged
		pass
	
	def radioButtonConstant_CheckChanged( self, event ):
		# TODO: Implement radioButtonConstant_CheckChanged
		pass
	
	def radioButtonVariable_CheckChanged( self, event ):
		# TODO: Implement radioButtonVariable_CheckChanged
		pass
	
	def comboBoxVariable_Clicked( self, event ):
		# TODO: Implement comboBoxVariable_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
