"""Subclass of ChooseAudio_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChooseAudio_Dialog
class ARCedChooseAudio_Dialog( ARCed_Templates.ChooseAudio_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ChooseAudio_Dialog.__init__( self, parent )
	
	# Handlers for ChooseAudio_Dialog events.
	def buttonPlay_Clicked( self, event ):
		# TODO: Implement buttonPlay_Clicked
		pass
	
	def buttonStop_Clicked( self, event ):
		# TODO: Implement buttonStop_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
