"""Subclass of AnimationTweening_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing AnimationTweening_Dialog
class ARCedAnimationTweening_Dialog( ARCed_Templates.AnimationTweening_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.AnimationTweening_Dialog.__init__( self, parent )
	
	# Handlers for AnimationTweening_Dialog events.
	def spinCtrlFramesStart_ValueChanged( self, event ):
		# TODO: Implement spinCtrlFramesStart_ValueChanged
		pass
	
	def spinCtrlFramesEnd_ValueChanged( self, event ):
		# TODO: Implement spinCtrlFramesEnd_ValueChanged
		pass
	
	def spinCtrlCellsStart_ValueChanged( self, event ):
		# TODO: Implement spinCtrlCellsStart_ValueChanged
		pass
	
	def spinCtrlCellsEnd_ValueChanged( self, event ):
		# TODO: Implement spinCtrlCellsEnd_ValueChanged
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
