"""Subclass of ShowText_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ShowText_Dialog
class ARCedShowText_Dialog( ARCed_Templates.ShowText_Dialog ):
	def __init__( self, parent ):
		ARCed_Templates.ShowText_Dialog.__init__( self, parent )
	
	# Handlers for ShowText_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
