"""Subclass of ChangeMaximum_Dialog, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing ChangeMaximum_Dialog
class ARCedChangeMaximum_Dialog( ARCed_Templates.ChangeMaximum_Dialog ):
	def __init__( self, parent, currentMaximum ):
		ARCed_Templates.ChangeMaximum_Dialog.__init__( self, parent )
		self.spinCtrlMaximum.SetValue(currentMaximum)

	# Handlers for ChangeMaximum_Dialog events.
	def buttonOK_Clicked( self, event ):
		self.EndModal(wx.ID_OK)

	def buttonCancel_Clicked( self, event ):
		self.EndModal(wx.ID_CANCEL)


