"""Subclass of BattleTest_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing BattleTest_Dialog
from PyitectConsumes import BattleTest_Dialog_Template


class BattleTest_Dialog(BattleTest_Dialog_Template):

    def __init__(self, parent):
        BattleTest_Dialog_Template.__init__(self, parent)

    # Handlers for BattleTest_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
