"""Subclass of ChangeBlending_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeBlending_Dialog
from PyitectConsumes import ChangeBlending_Dialog_Template


class ChangeBlending_Dialog(ChangeBlending_Dialog_Template):

    def __init__(self, parent):
        ChangeBlending_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeBlending_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
