"""Subclass of ChangeFrequency_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeFrequency_Dialog
from PyitectConsumes import ChangeFrequency_Dialog_Template


class ChangeFrequency_Dialog(ChangeFrequency_Dialog_Template):

    def __init__(self, parent):
        ChangeFrequency_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeFrequency_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
