"""Subclass of Comment_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing Comment_Dialog


from PyitectConsumes import Comment_Dialog_Template


class Comment_Dialog(Comment_Dialog_Template):

    def __init__(self, parent):
        Comment_Dialog_Template.__init__(self, parent)

    # Handlers for Comment_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
