"""Subclass of ControlSwitches_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ControlSwitches_Dialog


from PyitectConsumes import ControlSwitches_Dialog_Template


class ControlSwitches_Dialog(ControlSwitches_Dialog_Template):

    def __init__(self, parent):
        ControlSwitches_Dialog_Template.__init__(self, parent)

    # Handlers for ControlSwitches_Dialog events.
    def spinCtrlBatchStart_ValueChanged(self, event):
        # TODO: Implement spinCtrlBatchStart_ValueChanged
        pass

    def spinCtrlBatchEnd_ValueChanged(self, event):
        # TODO: Implement spinCtrlBatchEnd_ValueChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
