"""Subclass of ControlSelfSwitches_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ControlSelfSwitches_Dialog


from PyitectConsumes import ControlSelfSwitches_Dialog_Template


class ControlSelfSwitches_Dialog(ControlSelfSwitches_Dialog_Template):

    def __init__(self, parent):
        ControlSelfSwitches_Dialog_Template.__init__(self, parent)

    # Handlers for ControlSelfSwitches_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
