"""Subclass of ShopProcessing_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ShopProcessing_Dialog
from PyitectConsumes import ShopProcessing_Dialog_Template


class ShopProcessing_Dialog(ShopProcessing_Dialog_Template):

    def __init__(self, parent):
        ShopProcessing_Dialog_Template.__init__(self, parent)

    # Handlers for ShopProcessing_Dialog events.
    def listCtrlShopGoods_DoubleClick(self, event):
        # TODO: Implement listCtrlShopGoods_DoubleClick
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
