"""Subclass of TransferPlayerTilemap_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing TransferPlayerTilemap_Dialog
from PyitectConsumes import TransferPlayerTilemap_Dialog_Template


class TransferPlayerTilemap_Dialog(TransferPlayerTilemap_Dialog_Template):

    def __init__(self, parent):
        TransferPlayerTilemap_Dialog_Template.__init__(self, parent)

    # Handlers for TransferPlayerTilemap_Dialog events.
    def treeCtrlMaps_SelectionChanged(self, event):
        # TODO: Implement treeCtrlMaps_SelectionChanged
        pass

    def buttonFull_Clicked(self, event):
        # TODO: Implement buttonFull_Clicked
        pass

    def buttonThreeQuarter_Clicked(self, event):
        # TODO: Implement buttonThreeQuarter_Clicked
        pass

    def buttonHalf_Clicked(self, event):
        # TODO: Implement buttonHalf_Clicked
        pass

    def buttonQuarter_Clicked(self, event):
        # TODO: Implement buttonQuarter_Clicked
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
