"""Subclass of ChangeBlending_Dialog, which is generated by wxFormBuilder."""

import wx
from Boot import WelderImport

Kernel = WelderImport('Kernel')
Core = WelderImport('Core')

Templates = Core.Database.Welder_Templates

# Implementing ChangeBlending_Dialog
class ChangeBlending_Dialog( Templates.ChangeBlending_Dialog ):
	def __init__( self, parent ):
		Templates.ChangeBlending_Dialog.__init__( self, parent )
	
	# Handlers for ChangeBlending_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
