"""Subclass of ShopGoods_Dialog, which is generated by wxFormBuilder."""

import wx
from Boot import WelderImport

Kernel = WelderImport('Kernel')
Core = WelderImport('Core')

Templates = Core.Database.Welder_Templates

# Implementing ShopGoods_Dialog
class ShopGoods_Dialog( Templates.ShopGoods_Dialog ):
	def __init__( self, parent ):
		Templates.ShopGoods_Dialog.__init__( self, parent )
	
	# Handlers for ShopGoods_Dialog events.
	def radioButtonItem_CheckChanged( self, event ):
		# TODO: Implement radioButtonItem_CheckChanged
		pass
	
	def radioButtonWeapon_CheckChanged( self, event ):
		# TODO: Implement radioButtonWeapon_CheckChanged
		pass
	
	def radioButtonArmor_CheckChanged( self, event ):
		# TODO: Implement radioButtonArmor_CheckChanged
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
