"""Subclass of EventPage_Panel, which is generated by wxFormBuilder."""

import wx
from Boot import WelderImport

Kernel = WelderImport('Kernel')
Core = WelderImport('Core')

Templates = Core.Database.Welder_Templates

# Implementing EventPage_Panel
class EventPage_Panel( Templates.EventPage_Panel ):
    def __init__( self, parent ):
        Templates.EventPage_Panel.__init__( self, parent )
    
