"""Subclass of EventCommands3_Panel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing EventCommands3_Panel
class EventCommands3_Panel(ARCed_Templates.EventCommands3_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.EventCommands3_Panel.__init__( self, parent )
	
	# Handlers for EventCommands3_Panel events.
	def buttonChangeTransparency_Clicked( self, event ):
		# TODO: Implement buttonChangeTransparency_Clicked
		pass
	
	def buttonShowAnimation_Clicked( self, event ):
		# TODO: Implement buttonShowAnimation_Clicked
		pass
	
	def buttonEraseEvent_Clicked( self, event ):
		# TODO: Implement buttonEraseEvent_Clicked
		pass
	
	def buttonChangeHP_Clicked( self, event ):
		# TODO: Implement buttonChangeHP_Clicked
		pass
	
	def buttonChangeSP_Clicked( self, event ):
		# TODO: Implement buttonChangeSP_Clicked
		pass
	
	def buttonChangeState_Clicked( self, event ):
		# TODO: Implement buttonChangeState_Clicked
		pass
	
	def buttonRecoverAll_Clicked( self, event ):
		# TODO: Implement buttonRecoverAll_Clicked
		pass
	
	def buttonChangeExperience_Clicked( self, event ):
		# TODO: Implement buttonChangeExperience_Clicked
		pass
	
	def buttonChangeLevel_Clicked( self, event ):
		# TODO: Implement buttonChangeLevel_Clicked
		pass
	
	def buttonChangeParameters_Clicked( self, event ):
		# TODO: Implement buttonChangeParameters_Clicked
		pass
	
	def buttonChangeSkills_Clicked( self, event ):
		# TODO: Implement buttonChangeSkills_Clicked
		pass
	
	def buttonChangeEquipment_Clicked( self, event ):
		# TODO: Implement buttonChangeEquipment_Clicked
		pass
	
	def buttonChangeActorName_Clicked( self, event ):
		# TODO: Implement buttonChangeActorName_Clicked
		pass
	
	def buttonChangeActorClass_Clicked( self, event ):
		# TODO: Implement buttonChangeActorClass_Clicked
		pass
	
	def buttonChangeActorGraphic_Clicked( self, event ):
		# TODO: Implement buttonChangeActorGraphic_Clicked
		pass
	
	def buttonShowPicture_Clicked( self, event ):
		# TODO: Implement buttonShowPicture_Clicked
		pass
	
	def buttonMovePicture_Clicked( self, event ):
		# TODO: Implement buttonMovePicture_Clicked
		pass
	
	def buttonRotatePicture_Clicked( self, event ):
		# TODO: Implement buttonRotatePicture_Clicked
		pass
	
	def buttonChangePictureColorTone_Clicked( self, event ):
		# TODO: Implement buttonChangePictureColorTone_Clicked
		pass
	
	def buttonErasePicture_Clicked( self, event ):
		# TODO: Implement buttonErasePicture_Clicked
		pass
	
	def buttonChangeEnemyHP_Clicked( self, event ):
		# TODO: Implement buttonChangeEnemyHP_Clicked
		pass
	
	def buttonChangeEnemySP_Clicked( self, event ):
		# TODO: Implement buttonChangeEnemySP_Clicked
		pass
	
	def buttonChangeEnemyState_Clicked( self, event ):
		# TODO: Implement buttonChangeEnemyState_Clicked
		pass
	
	def buttonEnemyRecoverAll_Clicked( self, event ):
		# TODO: Implement buttonEnemyRecoverAll_Clicked
		pass
	
	def buttonEnemyAppearance_Clicked( self, event ):
		# TODO: Implement buttonEnemyAppearance_Clicked
		pass
	
	def buttonEnemyTransform_Clicked( self, event ):
		# TODO: Implement buttonEnemyTransform_Clicked
		pass
	
	def buttonShowBattleAnimation_Clicked( self, event ):
		# TODO: Implement buttonShowBattleAnimation_Clicked
		pass
	
	def buttonDealDamage_Clicked( self, event ):
		# TODO: Implement buttonDealDamage_Clicked
		pass
	
	def buttonForceAction_Clicked( self, event ):
		# TODO: Implement buttonForceAction_Clicked
		pass
	
	def buttonAbortBattle_Clicked( self, event ):
		# TODO: Implement buttonAbortBattle_Clicked
		pass
	
	
