"""Subclass of EventPage_Panel, which is generated by wxFormBuilder."""

import wx
import Database.ARCed_Templates as Templates

# Implementing EventPage_Panel
class EventPage_Panel( Templates.EventPage_Panel ):
	def __init__( self, parent ):
		ARCed_Templates.EventPage_Panel.__init__( self, parent )
	
