"""Subclass of FindReplacePanel, which is generated by wxFormBuilder."""

import wx
import ARCed_Templates

# Implementing FindReplacePanel
class FindReplacePanel( ARCed_Templates.FindReplacePanel ):
	def __init__( self, parent ):
		ARCed_Templates.FindReplacePanel.__init__( self, parent )
	
	# Handlers for FindReplacePanel events.
	def noteBookFindReplace_PageChanged( self, event ):
		# TODO: Implement noteBookFindReplace_PageChanged
		pass
	
	def comboBoxLook_SelectionChanged( self, event ):
		# TODO: Implement comboBoxLook_SelectionChanged
		pass
	
	def checkBoxMatchCase_CheckChanged( self, event ):
		# TODO: Implement checkBoxMatchCase_CheckChanged
		pass
	
	def checkBoxWholeWord_CheckChanged( self, event ):
		# TODO: Implement checkBoxWholeWord_CheckChanged
		pass
	
	def checkBoxSearchUP_CheckChanged( self, event ):
		# TODO: Implement checkBoxSearchUP_CheckChanged
		pass
	
	def checkBoxFlags_CheckChanged( self, event ):
		# TODO: Implement checkBoxFlags_CheckChanged
		pass
	
	def comboBoxFlags_SelectionChanged( self, event ):
		# TODO: Implement comboBoxFlags_SelectionChanged
		pass
	
	def buttonFindNext_Clicked( self, event ):
		# TODO: Implement buttonFindNext_Clicked
		pass
	
	def buttonReplace_Clicked( self, event ):
		# TODO: Implement buttonReplace_Clicked
		pass
	
	def buttonReplaceAll_Clicked( self, event ):
		# TODO: Implement buttonReplaceAll_Clicked
		pass
	
	
