"""Subclass of ScrollMap_Dialog, which is generated by wxFormBuilder."""

import wx
from Boot import WelderImport

Kernel = WelderImport('Kernel')
Core = WelderImport('Core')

Templates = Core.Database.Welder_Templates

# Implementing ScrollMap_Dialog
class ScrollMap_Dialog( Templates.ScrollMap_Dialog ):
	def __init__( self, parent ):
		Templates.ScrollMap_Dialog.__init__( self, parent )
	
	# Handlers for ScrollMap_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
