"""Subclass of ChangeTextOptions_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeTextOptions_Dialog
from PyitectConsumes import ChangeTextOptions_Dialog_Template


class ChangeTextOptions_Dialog(ChangeTextOptions_Dialog_Template):

    def __init__(self, parent):
        ChangeTextOptions_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeTextOptions_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
