"""Subclass of ChangeEquipment_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeEquipment_Dialog
from PyitectConsumes import ChangeEquipment_Dialog_Template


class ChangeEquipment_Dialog(ChangeEquipment_Dialog_Template):

    def __init__(self, parent):
        ChangeEquipment_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeEquipment_Dialog events.
    def radioButtonWeapon_CheckChanged(self, event):
        # TODO: Implement radioButtonWeapon_CheckChanged
        pass

    def radioButtonShield_CheckChanged(self, event):
        # TODO: Implement radioButtonShield_CheckChanged
        pass

    def radioButtonHelmet_CheckChanged(self, event):
        # TODO: Implement radioButtonHelmet_CheckChanged
        pass

    def radioButtonArmor_CheckChanged(self, event):
        # TODO: Implement radioButtonArmor_CheckChanged
        pass

    def radioButtonAccessory_CheckChanged(self, event):
        # TODO: Implement radioButtonAccessory_CheckChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
