"""Subclass of ChooseSwitchVariable_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel




# Implementing ChooseSwitchVariable_Dialog


from PyitectConsumes import ChooseSwitchVariable_Dialog_Template


class ChooseSwitchVariable_Dialog(ChooseSwitchVariable_Dialog_Template):

    def __init__(self, parent):
        ChooseSwitchVariable_Dialog_Template.__init__(self, parent)

    # Handlers for ChooseSwitchVariable_Dialog events.
    def listBoxGroup_SelectionChanged(self, event):
        # TODO: Implement listBoxGroup_SelectionChanged
        pass

    def buttonMax_Clicked(self, event):
        # TODO: Implement buttonMax_Clicked
        pass

    def listBoxItems_SelectionChanged(self, event):
        # TODO: Implement listBoxItems_SelectionChanged
        pass

    def textCtrlName_TextChanged(self, event):
        # TODO: Implement textCtrlName_TextChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass

    def buttonApply_Clicked(self, event):
        # TODO: Implement buttonApply_Clicked
        pass
