"""Subclass of ControlTimer_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ControlTimer_Dialog


from PyitectConsumes import ControlTimer_Dialog_Template


class ControlTimer_Dialog(ControlTimer_Dialog_Template):

    def __init__(self, parent):
        ControlTimer_Dialog_Template.__init__(self, parent)

    # Handlers for ControlTimer_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
