"""Subclass of EnemyTransform_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing EnemyTransform_Dialog


class EnemyTransform_Dialog(Templates.EnemyTransform_Dialog):

    def __init__(self, parent):
        Templates.EnemyTransform_Dialog.__init__(self, parent)

    # Handlers for EnemyTransform_Dialog events.
    def comboBoxEnemy_Clicked(self, event):
        # TODO: Implement comboBoxEnemy_Clicked
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
