"""Subclass of EnemyAppearance_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing EnemyAppearance_Dialog


from PyitectConsumes import EnemyAppearance_Dialog_Template


class EnemyAppearance_Dialog(EnemyAppearance_Dialog_Template):

    def __init__(self, parent):
        EnemyAppearance_Dialog_Template.__init__(self, parent)

    # Handlers for EnemyAppearance_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
