"""Subclass of InputNumber_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing InputNumber_Dialog


from PyitectConsumes import InputNumber_Dialog_Template


class InputNumber_Dialog(InputNumber_Dialog_Template):

    def __init__(self, parent):
        InputNumber_Dialog_Template.__init__(self, parent)

    # Handlers for InputNumber_Dialog events.
    def comboBoxVariable_Clicked(self, event):
        # TODO: Implement comboBoxVariable_Clicked
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
