"""Subclass of MoveRoute_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing MoveRoute_Dialog


from PyitectConsumes import MoveRoute_Dialog_Template


class MoveRoute_Dialog(MoveRoute_Dialog_Template):

    def __init__(self, parent):
        MoveRoute_Dialog_Template.__init__(self, parent)

    # Handlers for MoveRoute_Dialog events.
    def listBoxMoveRoute_OnChar(self, event):
        # TODO: Implement listBoxMoveRoute_OnChar
        pass

    def buttonMoveDown_Clicked(self, event):
        # TODO: Implement buttonMoveDown_Clicked
        pass

    def buttonMoveLeft_Clicked(self, event):
        # TODO: Implement buttonMoveLeft_Clicked
        pass

    def buttonMoveRight_Clicked(self, event):
        # TODO: Implement buttonMoveRight_Clicked
        pass

    def buttonMoveUp_Clicked(self, event):
        # TODO: Implement buttonMoveUp_Clicked
        pass

    def buttonMoveLowerLeft_Clicked(self, event):
        # TODO: Implement buttonMoveLowerLeft_Clicked
        pass

    def buttonMoveLowerRight_Clicked(self, event):
        # TODO: Implement buttonMoveLowerRight_Clicked
        pass

    def buttonMoveUpperLeft_Clicked(self, event):
        # TODO: Implement buttonMoveUpperLeft_Clicked
        pass

    def buttonMoveUpperRight_Clicked(self, event):
        # TODO: Implement buttonMoveUpperRight_Clicked
        pass

    def buttonMoveRandom_Clicked(self, event):
        # TODO: Implement buttonMoveRandom_Clicked
        pass

    def buttonMoveTowardPlayer_Clicked(self, event):
        # TODO: Implement buttonMoveTowardPlayer_Clicked
        pass

    def buttonMoveAwayPlayer_Clicked(self, event):
        # TODO: Implement buttonMoveAwayPlayer_Clicked
        pass

    def buttonStepForward_Clicked(self, event):
        # TODO: Implement buttonStepForward_Clicked
        pass

    def buttonStepBackward_Clicked(self, event):
        # TODO: Implement buttonStepBackward_Clicked
        pass

    def buttonJump_Clicked(self, event):
        # TODO: Implement buttonJump_Clicked
        pass

    def buttonWait_Clicked(self, event):
        # TODO: Implement buttonWait_Clicked
        pass

    def buttonTurnDown_Clicked(self, event):
        # TODO: Implement buttonTurnDown_Clicked
        pass

    def buttonTurnLeft_Clicked(self, event):
        # TODO: Implement buttonTurnLeft_Clicked
        pass

    def buttonTurnRight_Clicked(self, event):
        # TODO: Implement buttonTurnRight_Clicked
        pass

    def buttonTurnUp_Clicked(self, event):
        # TODO: Implement buttonTurnUp_Clicked
        pass

    def buttonTurn90Left_Clicked(self, event):
        # TODO: Implement buttonTurn90Left_Clicked
        pass

    def buttonTurn90Right_Clicked(self, event):
        # TODO: Implement buttonTurn90Right_Clicked
        pass

    def buttonTurn180_Clicked(self, event):
        # TODO: Implement buttonTurn180_Clicked
        pass

    def buttonTurn90_Clicked(self, event):
        # TODO: Implement buttonTurn90_Clicked
        pass

    def buttonTurnRandom_Clicked(self, event):
        # TODO: Implement buttonTurnRandom_Clicked
        pass

    def buttonTurnTowardPlayer_Clicked(self, event):
        # TODO: Implement buttonTurnTowardPlayer_Clicked
        pass

    def buttonTurnAwayPlayer_Clicked(self, event):
        # TODO: Implement buttonTurnAwayPlayer_Clicked
        pass

    def buttonSwitchOn_Clicked(self, event):
        # TODO: Implement buttonSwitchOn_Clicked
        pass

    def buttonSwitchOff_Clicked(self, event):
        # TODO: Implement buttonSwitchOff_Clicked
        pass

    def buttonChangeSpeed_Clicked(self, event):
        # TODO: Implement buttonChangeSpeed_Clicked
        pass

    def buttonChangeFreq_Clicked(self, event):
        # TODO: Implement buttonChangeFreq_Clicked
        pass

    def buttonMoveAnimationOn_Clicked(self, event):
        # TODO: Implement buttonMoveAnimationOn_Clicked
        pass

    def buttonMoveAnimationOff_Clicked(self, event):
        # TODO: Implement buttonMoveAnimationOff_Clicked
        pass

    def buttonStopAnimationOn_Clicked(self, event):
        # TODO: Implement buttonStopAnimationOn_Clicked
        pass

    def buttonStopAnimationOff_Clicked(self, event):
        # TODO: Implement buttonStopAnimationOff_Clicked
        pass

    def buttonDirectionFixOn_Clicked(self, event):
        # TODO: Implement buttonDirectionFixOn_Clicked
        pass

    def buttonDirectionFixOff_Clicked(self, event):
        # TODO: Implement buttonDirectionFixOff_Clicked
        pass

    def buttonThroughOn_Clicked(self, event):
        # TODO: Implement buttonThroughOn_Clicked
        pass

    def buttonThroughOff_Clicked(self, event):
        # TODO: Implement buttonThroughOff_Clicked
        pass

    def buttonAlwaysTopOn_Clicked(self, event):
        # TODO: Implement buttonAlwaysTopOn_Clicked
        pass

    def buttonAlwaysTopOff_Clicked(self, event):
        # TODO: Implement buttonAlwaysTopOff_Clicked
        pass

    def buttonChangeGraphic_Clicked(self, event):
        # TODO: Implement buttonChangeGraphic_Clicked
        pass

    def buttonChangeOpacity_Clicked(self, event):
        # TODO: Implement buttonChangeOpacity_Clicked
        pass

    def buttonChangeBlending_Clicked(self, event):
        # TODO: Implement buttonChangeBlending_Clicked
        pass

    def buttonPlaySE_Clicked(self, event):
        # TODO: Implement buttonPlaySE_Clicked
        pass

    def buttonScript_Clicked(self, event):
        # TODO: Implement buttonScript_Clicked
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
