"""Subclass of RotatePicture_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel




# Implementing RotatePicture_Dialog


from PyitectConsumes import RotatePicture_Dialog_Template


class RotatePicture_Dialog(RotatePicture_Dialog_Template):

    def __init__(self, parent):
        RotatePicture_Dialog_Template.__init__(self, parent)

    # Handlers for RotatePicture_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
