"""Subclass of ScrollMap_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ScrollMap_Dialog
from PyitectConsumes import ScrollMap_Dialog_Template


class ScrollMap_Dialog(ScrollMap_Dialog_Template):

    def __init__(self, parent):
        ScrollMap_Dialog_Template.__init__(self, parent)

    # Handlers for ScrollMap_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
