"""Subclass of ShopGoods_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ShopGoods_Dialog
from PyitectConsumes import ShopGoods_Dialog_Template


class ShopGoods_Dialog(ShopGoods_Dialog_Template):

    def __init__(self, parent):
        ShopGoods_Dialog_Template.__init__(self, parent)

    # Handlers for ShopGoods_Dialog events.
    def radioButtonItem_CheckChanged(self, event):
        # TODO: Implement radioButtonItem_CheckChanged
        pass

    def radioButtonWeapon_CheckChanged(self, event):
        # TODO: Implement radioButtonWeapon_CheckChanged
        pass

    def radioButtonArmor_CheckChanged(self, event):
        # TODO: Implement radioButtonArmor_CheckChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
