"""Subclass of TransparentFlag_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing TransparentFlag_Dialog
from PyitectConsumes import TransparentFlag_Dialog_Template


class TransparentFlag_Dialog(TransparentFlag_Dialog_Template):

    def __init__(self, parent):
        TransparentFlag_Dialog_Template.__init__(self, parent)

    # Handlers for TransparentFlag_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
