"""Subclass of ButonProcessing_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ButonProcessing_Dialog
from PyitectConsumes import ButtonProcessing_Dialog_Template


class ButonProcessing_Dialog(ButtonProcessing_Dialog_Template):

    def __init__(self, parent):
        ButonProcessing_Dialog_Template.__init__(self, parent)

    # Handlers for ButonProcessing_Dialog events.
    def comboBoxVariable_Clicked(self, event):
        # TODO: Implement comboBoxVariable_Clicked
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
