"""Subclass of ChangePartyMember_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangePartyMember_Dialog
from PyitectConsumes import ChangePartyMember_Dialog_Template


class ChangePartyMember_Dialog(ChangePartyMember_Dialog_Template):

    def __init__(self, parent):
        ChangePartyMember_Dialog_Template.__init__(self, parent)

    # Handlers for ChangePartyMember_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
