"""Subclass of ChangeActorName_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeActorName_Dialog
from PyitectConsumes import ChangeActorName_Dialog_Template


class ChangeActorName_Dialog(ChangeActorName_Dialog_Template):

    def __init__(self, parent):
        ChangeActorName_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeActorName_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
