"""Subclass of ChangeSpeed_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeSpeed_Dialog
from PyitectConsumes import ChangeSpeed_Dialog_Template


class ChangeSpeed_Dialog(ChangeSpeed_Dialog_Template):

    def __init__(self, parent):
        ChangeSpeed_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeSpeed_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
