"""Subclass of ChangeState_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeState_Dialog
from PyitectConsumes import ChangeState_Dialog_Template


class ChangeState_Dialog(ChangeState_Dialog_Template):

    def __init__(self, parent):
        ChangeState_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeState_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
