"""Subclass of ChangelGold_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangelGold_Dialog
from PyitectConsumes import ChangelGold_Dialog_Template


class ChangelGold_Dialog(ChangelGold_Dialog_Template):

    def __init__(self, parent):
        ChangelGold_Dialog_Template.__init__(self, parent)

    # Handlers for ChangelGold_Dialog events.
    def radioButtonConstant_CheckChanged(self, event):
        # TODO: Implement radioButtonConstant_CheckChanged
        pass

    def radioButtonVariable_CheckChanged(self, event):
        # TODO: Implement radioButtonVariable_CheckChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
