"""Subclass of ChangeState_Dialog, which is generated by wxFormBuilder."""

import wx
from Boot import WelderImport

Kernel = WelderImport('Kernel')
Core = WelderImport('Core')

Templates = Core.Database.Welder_Templates

# Implementing ChangeState_Dialog
class ChangeState_Dialog( Templates.ChangeState_Dialog ):
	def __init__( self, parent ):
		Templates.ChangeState_Dialog.__init__( self, parent )
	
	# Handlers for ChangeState_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
