"""Subclass of ChangeStat_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeStat_Dialog
from PyitectConsumes import ChangeStat_Dialog_Template


class ChangeStat_Dialog(ChangeStat_Dialog_Template):

    def __init__(self, parent):
        ChangeStat_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeStat_Dialog events.
    def radioButtonConstant_CheckChanged(self, event):
        # TODO: Implement radioButtonConstant_CheckChanged
        pass

    def radioButtonVariable_CheckChanged(self, event):
        # TODO: Implement radioButtonVariable_CheckChanged
        pass

    def comboBoxVariable_Clicked(self, event):
        # TODO: Implement comboBoxVariable_Clicked
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
