"""Subclass of ChangeFogOpacity_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeFogOpacity_Dialog
class ChangeFogOpacity_Dialog(Templates.ChangeFogOpacity_Dialog):

    def __init__(self, parent):
        Templates.ChangeFogOpacity_Dialog.__init__(self, parent)

    # Handlers for ChangeFogOpacity_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
