"""Subclass of ChooseActor_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChooseActor_Dialog
from PyitectConsumes import ChooseActor_Dialog_Template


class ChooseActor_Dialog(ChooseActor_Dialog_Template):

    def __init__(self, parent):
        ChooseActor_Dialog_Template.__init__(self, parent)

    # Handlers for ChooseActor_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
