"""Subclass of ControlVariables_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ControlVariables_Dialog


class ControlVariables_Dialog(Templates.ControlVariables_Dialog):

    def __init__(self, parent):
        Templates.ControlVariables_Dialog.__init__(self, parent)

    # Handlers for ControlVariables_Dialog events.
    def spinCtrlBatchStart_ValueChanged(self, event):
        # TODO: Implement spinCtrlBatchStart_ValueChanged
        pass

    def spinCtrlBatchEnd_ValueChanged(self, event):
        # TODO: Implement spinCtrlBatchEnd_ValueChanged
        pass

    def radioButtonConstant_CheckChanged(self, event):
        # TODO: Implement radioButtonConstant_CheckChanged
        pass

    def radioButtonVariable_CheckChanged(self, event):
        # TODO: Implement radioButtonVariable_CheckChanged
        pass

    def radioButtonRandom_CheckChanged(self, event):
        # TODO: Implement radioButtonRandom_CheckChanged
        pass

    def radioButtonItem_CheckChanged(self, event):
        # TODO: Implement radioButtonItem_CheckChanged
        pass

    def radioButtonActor_CheckChanged(self, event):
        # TODO: Implement radioButtonActor_CheckChanged
        pass

    def radioButtonEnemy_CheckChanged(self, event):
        # TODO: Implement radioButtonEnemy_CheckChanged
        pass

    def radioButtonCharacter_CheckChanged(self, event):
        # TODO: Implement radioButtonCharacter_CheckChanged
        pass

    def radioButtonOther_CheckChanged(self, event):
        # TODO: Implement radioButtonOther_CheckChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
