"""Subclass of ErasePicture_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ErasePicture_Dialog


from PyitectConsumes import ErasePicture_Dialog_Template


class ErasePicture_Dialog(ErasePicture_Dialog_Template):

    def __init__(self, parent):
        ErasePicture_Dialog_Template.__init__(self, parent)

    # Handlers for ErasePicture_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
