"""Subclass of EventCondition_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing EventCondition_Dialog


from PyitectConsumes import EventCondition_Dialog_Template


class EventCondition_Dialog(EventCondition_Dialog_Template):

    def __init__(self, parent):
        EventCondition_Dialog_Template.__init__(self, parent)

    # Handlers for EventCondition_Dialog events.
    def checkBoxTurn_CheckChanged(self, event):
        # TODO: Implement checkBoxTurn_CheckChanged
        pass

    def checkBoxEnemy_CheckChanged(self, event):
        # TODO: Implement checkBoxEnemy_CheckChanged
        pass

    def checkBoxActor_CheckChanged(self, event):
        # TODO: Implement checkBoxActor_CheckChanged
        pass

    def checkBoxSwitch_CheckChanged(self, event):
        # TODO: Implement checkBoxSwitch_CheckChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
