"""Subclass of FadeOutAudio_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing FadeOutAudio_Dialog


from PyitectConsumes import FadeOutAudio_Dialog_Template


class FadeOutAudio_Dialog(FadeOutAudio_Dialog_Template):

    def __init__(self, parent):
        FadeOutAudio_Dialog_Template.__init__(self, parent)

    # Handlers for FadeOutAudio_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
