"""Subclass of Jump_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing Jump_Dialog


from PyitectConsumes import Jump_Dialog_Template


class Jump_Dialog(Jump_Dialog_Template):

    def __init__(self, parent):
        Jump_Dialog_Template.__init__(self, parent)

    # Handlers for Jump_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
