"""Subclass of Label_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing Label_Dialog


from PyitectConsumes import Label_Dialog_Template


class Label_Dialog(Label_Dialog_Template):

    def __init__(self, parent):
        Label_Dialog_Template.__init__(self, parent)

    # Handlers for Label_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
