"""Subclass of MovePicture_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing MovePicture_Dialog


from PyitectConsumes import MovePicture_Dialog_Template


class MovePicture_Dialog(MovePicture_Dialog_Template):

    def __init__(self, parent):
        MovePicture_Dialog_Template.__init__(self, parent)

    # Handlers for MovePicture_Dialog events.
    def radioButtonConstant_CheckChanged(self, event):
        # TODO: Implement radioButtonConstant_CheckChanged
        pass

    def radioButtonVariable_CheckChanged(self, event):
        # TODO: Implement radioButtonVariable_CheckChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
