"""Subclass of NameProcessing_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing NameProcessing_Dialog


from PyitectConsumes import NameProcessing_Dialog_Template


class NameProcessing_Dialog(NameProcessing_Dialog_Template):

    def __init__(self, parent):
        NameProcessing_Dialog_Template.__init__(self, parent)

    # Handlers for NameProcessing_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
