"""Subclass of RecoverAll_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing RecoverAll_Dialog


from PyitectConsumes import RecoverAll_Dialog_Template


class RecoverAll_Dialog(RecoverAll_Dialog_Template):

    def __init__(self, parent):
        RecoverAll_Dialog_Template.__init__(self, parent)

    # Handlers for RecoverAll_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
