"""Subclass of ScriptCall_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ScriptCall_Dialog
from PyitectConsumes import ScriptCall_Dialog_Template


class ScriptCall_Dialog(ScriptCall_Dialog_Template):

    def __init__(self, parent):
        ScriptCall_Dialog_Template.__init__(self, parent)

    # Handlers for ScriptCall_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
