"""Subclass of ShowText_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ShowText_Dialog
from PyitectConsumes import ShowText_Dialog_Template


class ShowText_Dialog(ShowText_Dialog_Template):

    def __init__(self, parent):
        ShowText_Dialog_Template.__init__(self, parent)

    # Handlers for ShowText_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
