"""Subclass of TransferEventTilemap_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing TransferEventTilemap_Dialog
from PyitectConsumes import TransferEventTilemap_Dialog_Template


class TransferEventTilemap_Dialog(TransferEventTilemap_Dialog_Template):

    def __init__(self, parent):
        TransferEventTilemap_Dialog_Template.__init__(self, parent)

    # Handlers for TransferEventTilemap_Dialog events.
    def buttonFull_Clicked(self, event):
        # TODO: Implement buttonFull_Clicked
        pass

    def buttonThreeQuarter_Clicked(self, event):
        # TODO: Implement buttonThreeQuarter_Clicked
        pass

    def buttonHalf_Clicked(self, event):
        # TODO: Implement buttonHalf_Clicked
        pass

    def buttonQuarter_Clicked(self, event):
        # TODO: Implement buttonQuarter_Clicked
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
