"""Subclass of WeatherEffects_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing WeatherEffects_Dialog
class WeatherEffects_Dialog(Templates.WeatherEffects_Dialog):

    def __init__(self, parent):
        Templates.WeatherEffects_Dialog.__init__(self, parent)

    # Handlers for WeatherEffects_Dialog events.
    def sliderPower_ScrollChanged(self, event):
        # TODO: Implement sliderPower_ScrollChanged
        pass

    def spinCtrlPower_ValueChanged(self, event):
        # TODO: Implement spinCtrlPower_ValueChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
