"""Subclass of BattleProcessing_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing BattleProcessing_Dialog
from PyitectConsumes import BattleProcessing_Dialog_Template


class BattleProcessing_Dialog(BattleProcessing_Dialog_Template):

    def __init__(self, parent):
        BattleProcessing_Dialog_Template.__init__(self, parent)

    # Handlers for BattleProcessing_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
