"""Subclass of ButtonProcessing_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ButtonProcessing_Dialog
from PyitectConsumes import ButtonProcessing_Dialog_Template


class ButtonProcessing_Dialog(ButtonProcessing_Dialog_Template):

    def __init__(self, parent):
        ButtonProcessing_Dialog_Template.__init__(self, parent)

    # Handlers for ButtonProcessing_Dialog events.
    def comboBoxVariable_Clicked(self, event):
        # TODO: Implement comboBoxVariable_Clicked
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
