"""Subclass of ChangeActorClass_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeActorClass_Dialog
from PyitectConsumes import ChangeActorClass_Dialog_Template


class ChangeActorClass_Dialog(ChangeActorClass_Dialog_Template):

    def __init__(self, parent):
        ChangeActorClass_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeActorClass_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
