"""Subclass of ChangeAccess_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeAccess_Dialog
from PyitectConsumes import ChangeAccess_Dialog_Template


class ChangeAccess_Dialog(ChangeAccess_Dialog_Template):

    def __init__(self, parent):
        ChangeAccess_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeAccess_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
