"""Subclass of ChangeFogOpacity_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeFogOpacity_Dialog
from PyitectConsumes import ChangeFogOpacity_Dialog_Template


class ChangeFogOpacity_Dialog(ChangeFogOpacity_Dialog_Template):

    def __init__(self, parent):
        ChangeFogOpacity_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeFogOpacity_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
