"""Subclass of ChangeSkills_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeSkills_Dialog
from PyitectConsumes import ChangeSkills_Dialog_Template


class ChangeSkills_Dialog(ChangeSkills_Dialog_Template):

    def __init__(self, parent):
        ChangeSkills_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeSkills_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
