"""Subclass of ChangeParameters_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ChangeParameters_Dialog
from PyitectConsumes import ChangeParameters_Dialog_Template


class ChangeParameters_Dialog(ChangeParameters_Dialog_Template):

    def __init__(self, parent):
        ChangeParameters_Dialog_Template.__init__(self, parent)

    # Handlers for ChangeParameters_Dialog events.
    def radioButtonConstant_CheckChanged(self, event):
        # TODO: Implement radioButtonConstant_CheckChanged
        pass

    def radioButtonVariable_CheckChanged(self, event):
        # TODO: Implement radioButtonVariable_CheckChanged
        pass

    def comboBoxVariable_Clicked(self, event):
        # TODO: Implement comboBoxVariable_Clicked
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
