"""Subclass of ScreenShake_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ScreenShake_Dialog
from PyitectConsumes import ScreenShake_Dialog_Template


class ScreenShake_Dialog(ScreenShake_Dialog_Template):

    def __init__(self, parent):
        ScreenShake_Dialog_Template.__init__(self, parent)

    # Handlers for ScreenShake_Dialog events.
    def sliderPower_ScrollChanged(self, event):
        # TODO: Implement sliderPower_ScrollChanged
        pass

    def spinCtrlPower_ValueChanged(self, event):
        # TODO: Implement spinCtrlPower_ValueChanged
        pass

    def sliderSpeed_ScrollChanged(self, event):
        # TODO: Implement sliderSpeed_ScrollChanged
        pass

    def spinCtrlSpeed_ValueChanged(self, event):
        # TODO: Implement spinCtrlSpeed_ValueChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
