"""Subclass of ShowChoices_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ShowChoices_Dialog
from PyitectConsumes import ShowChoices_Dialog_Template


class ShowChoices_Dialog(ShowChoices_Dialog_Template):

    def __init__(self, parent):
        ShowChoices_Dialog_Template.__init__(self, parent)

    # Handlers for ShowChoices_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
