"""Subclass of ShowAnimation_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing ShowAnimation_Dialog
from PyitectConsumes import ShowAnimation_Dialog_Template


class ShowAnimation_Dialog(ShowAnimation_Dialog_Template):

    def __init__(self, parent):
        ShowAnimation_Dialog_Template.__init__(self, parent)

    # Handlers for ShowAnimation_Dialog events.
    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
