"""Subclass of WeatherEffects_Dialog, which is generated by wxFormBuilder."""

import wx


import Kernel


# Implementing WeatherEffects_Dialog
from PyitectConsumes import WeatherEffects_Dialog_Template


class WeatherEffects_Dialog(WeatherEffects_Dialog_Template):

    def __init__(self, parent):
        WeatherEffects_Dialog_Template.__init__(self, parent)

    # Handlers for WeatherEffects_Dialog events.
    def sliderPower_ScrollChanged(self, event):
        # TODO: Implement sliderPower_ScrollChanged
        pass

    def spinCtrlPower_ValueChanged(self, event):
        # TODO: Implement spinCtrlPower_ValueChanged
        pass

    def buttonOK_Clicked(self, event):
        # TODO: Implement buttonOK_Clicked
        pass

    def buttonCancel_Clicked(self, event):
        # TODO: Implement buttonCancel_Clicked
        pass
