"""Subclass of ButtonProcessing_Dialog, which is generated by wxFormBuilder."""

import wx
from Boot import WelderImport

Kernel = WelderImport('Kernel')
Core = WelderImport('Core')

Templates = Core.Database.Welder_Templates

# Implementing ButtonProcessing_Dialog
class ButtonProcessing_Dialog( Templates.ButtonProcessing_Dialog ):
	def __init__( self, parent ):
		Templates.ButtonProcessing_Dialog.__init__( self, parent )
	
	# Handlers for ButtonProcessing_Dialog events.
	def comboBoxVariable_Clicked( self, event ):
		# TODO: Implement comboBoxVariable_Clicked
		pass
	
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
