"""Subclass of RecoverAll_Dialog, which is generated by wxFormBuilder."""

import wx
from Boot import WelderImport

Kernel = WelderImport('Kernel')
Core = WelderImport('Core')

Templates = Core.Database.Welder_Templates

# Implementing RecoverAll_Dialog
class RecoverAll_Dialog( Templates.RecoverAll_Dialog ):
	def __init__( self, parent ):
		Templates.RecoverAll_Dialog.__init__( self, parent )
	
	# Handlers for RecoverAll_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
