"""Subclass of RotatePicture_Dialog, which is generated by wxFormBuilder."""

import wx
from Boot import WelderImport

Kernel = WelderImport('Kernel')
Core = WelderImport('Core')

Templates = Core.Database.Welder_Templates

# Implementing RotatePicture_Dialog
class RotatePicture_Dialog( Templates.RotatePicture_Dialog ):
	def __init__( self, parent ):
		Templates.RotatePicture_Dialog.__init__( self, parent )
	
	# Handlers for RotatePicture_Dialog events.
	def buttonOK_Clicked( self, event ):
		# TODO: Implement buttonOK_Clicked
		pass
	
	def buttonCancel_Clicked( self, event ):
		# TODO: Implement buttonCancel_Clicked
		pass
	
	
